<#
.SYNOPSIS
  Writes INSERT statements for the given tables of a database into a .sql file, so reference
  data comes from a script that can be re-run instead of being copied between databases by
  hand.

.DESCRIPTION
  Every value is written as a typed literal: NVARCHAR as N'...' (so Arabic survives),
  decimals with an invariant culture, dates as ISO 8601. Identity columns keep their ids
  (SET IDENTITY_INSERT), which matters because other tables point at them.

  Each table is wrapped in "IF NOT EXISTS (SELECT 1 FROM t)", so re-running the file against
  a database that already has the data does nothing instead of failing or duplicating.

  The output is UTF-8 with a BOM. Apply it with:  sqlcmd -f 65001 -b -d <db> -i <file>

    .\scripts\db\generate-seed.ps1 -Database velora `
        -Tables role,governorate,shipping_zone,shipping_rate,shipping_zone_governorate `
        -Output src\main\resources\db\baseline\seed_reference_data.sql -Title '...'

  List the tables in foreign-key order: parents before children.
#>
param(
    [Parameter(Mandatory)] [string] $Database,
    [Parameter(Mandatory)] [string[]] $Tables,
    [Parameter(Mandatory)] [string] $Output,
    [string] $Title = 'seed data',
    [string] $Server = 'localhost,1433',
    [string] $User = 'sa',
    [string] $Password = $env:SQLCMDPASSWORD
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Data

$cs = "Server=$Server;Database=$Database;User ID=$User;Password=$Password;TrustServerCertificate=True;Encrypt=True"
$conn = New-Object System.Data.SqlClient.SqlConnection $cs
$conn.Open()

function Format-Value($value, [string] $typeName) {
    if ($value -is [System.DBNull]) { return 'NULL' }
    $inv = [System.Globalization.CultureInfo]::InvariantCulture
    switch -Regex ($typeName) {
        '^(nvarchar|nchar|ntext)$' { return "N'" + ([string]$value).Replace("'", "''") + "'" }
        '^(varchar|char|text)$'    { return "'" + ([string]$value).Replace("'", "''") + "'" }
        '^bit$'                    { return $(if ($value) { '1' } else { '0' }) }
        '^(tinyint|smallint|int|bigint)$' { return ([long]$value).ToString($inv) }
        '^(decimal|numeric|money|smallmoney)$' { return ([decimal]$value).ToString($inv) }
        '^(float|real)$'           { return ([double]$value).ToString('R', $inv) }
        '^datetimeoffset$'         { return "'" + ([DateTimeOffset]$value).ToString('yyyy-MM-dd HH:mm:ss.fffffffzzz', $inv) + "'" }
        '^(datetime|datetime2|smalldatetime)$' { return "'" + ([DateTime]$value).ToString('yyyy-MM-dd HH:mm:ss.fffffff', $inv) + "'" }
        '^date$'                   { return "'" + ([DateTime]$value).ToString('yyyy-MM-dd', $inv) + "'" }
        '^uniqueidentifier$'       { return "'" + $value.ToString() + "'" }
        default { throw "Type '$typeName' is not handled by generate-seed.ps1" }
    }
}

$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("/* =====================================================================")
[void]$out.AppendLine("   $Title")
[void]$out.AppendLine("")
[void]$out.AppendLine("   Generated by scripts/db/generate-seed.ps1 from the '$Database' database.")
[void]$out.AppendLine("   Re-running is harmless: a table that already has rows is left alone.")
[void]$out.AppendLine("   Apply with:  sqlcmd -f 65001 -b -d <database> -i <this file>")
[void]$out.AppendLine("   ===================================================================== */")
[void]$out.AppendLine("")
[void]$out.AppendLine("SET QUOTED_IDENTIFIER ON;")
[void]$out.AppendLine("GO")
[void]$out.AppendLine("")

foreach ($table in $Tables) {
    $schemaCmd = $conn.CreateCommand()
    $schemaCmd.CommandText = @"
SELECT c.name, ty.name AS type_name, c.is_identity, c.is_computed
FROM sys.columns c
JOIN sys.types ty ON ty.user_type_id = c.user_type_id
WHERE c.object_id = OBJECT_ID(N'dbo.$table')
ORDER BY c.column_id
"@
    $cols = @()
    $reader = $schemaCmd.ExecuteReader()
    while ($reader.Read()) {
        $cols += [pscustomobject]@{ Name = $reader['name']; Type = $reader['type_name']; Identity = [bool]$reader['is_identity']; Computed = [bool]$reader['is_computed'] }
    }
    $reader.Close()
    if ($cols.Count -eq 0) { throw "Table dbo.$table not found in $Database" }
    $cols = $cols | Where-Object { -not $_.Computed }
    $hasIdentity = [bool]($cols | Where-Object { $_.Identity })
    $colList = ($cols | ForEach-Object { "[$($_.Name)]" }) -join ', '

    $dataCmd = $conn.CreateCommand()
    $idCol = ($cols | Select-Object -First 1).Name
    $dataCmd.CommandText = "SELECT $colList FROM dbo.[$table] ORDER BY [$idCol]"
    $rows = New-Object System.Collections.Generic.List[string]
    $reader = $dataCmd.ExecuteReader()
    while ($reader.Read()) {
        $values = for ($i = 0; $i -lt $cols.Count; $i++) { Format-Value $reader.GetValue($i) $cols[$i].Type }
        $rows.Add("    ($($values -join ', '))")
    }
    $reader.Close()

    [void]$out.AppendLine("/* $table : $($rows.Count) row(s) */")
    if ($rows.Count -eq 0) { [void]$out.AppendLine("GO"); [void]$out.AppendLine(""); continue }
    [void]$out.AppendLine("IF NOT EXISTS (SELECT 1 FROM dbo.[$table])")
    [void]$out.AppendLine("BEGIN")
    if ($hasIdentity) { [void]$out.AppendLine("    SET IDENTITY_INSERT dbo.[$table] ON;") }
    [void]$out.AppendLine("    INSERT INTO dbo.[$table] ($colList) VALUES")
    [void]$out.AppendLine(($rows -join ",`r`n") + ";")
    if ($hasIdentity) { [void]$out.AppendLine("    SET IDENTITY_INSERT dbo.[$table] OFF;") }
    [void]$out.AppendLine("END")
    [void]$out.AppendLine("GO")
    [void]$out.AppendLine("")
}
$conn.Close()

$dir = Split-Path -Parent $Output
if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }
[System.IO.File]::WriteAllText($Output, $out.ToString(), (New-Object System.Text.UTF8Encoding($true)))
"Wrote $($Tables.Count) table(s) from '$Database' into $Output"
