<#
.SYNOPSIS
  Scripts a database's whole schema (no data) into one baseline .sql file.

.DESCRIPTION
  Uses SQL Server Management Objects (the SQLPS module that ships with SQL Server). Objects
  are written in dependency-safe order: tables first (with primary keys, unique, check and
  default constraints), then indexes, then foreign keys, then views - so the file runs on an
  empty database without any ordering problems.

  Constraints SQL Server named itself are written WITHOUT a name, so rebuilding the schema
  does not freeze arbitrary names like PK__invoice___06CDC815D485FDCD into the file.

  This is how src/main/resources/db/baseline/baseline_through_V14.sql was produced:
    .\scripts\db\generate-baseline.ps1 -Database velora -Output <file>
  It is kept so the baseline can be regenerated and, more usefully, checked: see
  compare-schemas.ps1.

.PARAMETER Password
  Defaults to the SQLCMDPASSWORD environment variable, so it never needs to be typed
  into a command line that ends up in shell history.
#>
param(
    [Parameter(Mandatory)] [string] $Database,
    [Parameter(Mandatory)] [string] $Output,
    [string] $Server = 'localhost,1433',
    [string] $User = 'sa',
    [string] $Password = $env:SQLCMDPASSWORD,
    [string] $Title = 'baseline'
)

$ErrorActionPreference = 'Stop'
Import-Module SQLPS -DisableNameChecking 2>$null | Out-Null

$srv = New-Object Microsoft.SqlServer.Management.Smo.Server $Server
$srv.ConnectionContext.LoginSecure = $false
$srv.ConnectionContext.set_Login($User)
$srv.ConnectionContext.set_Password($Password)
$srv.ConnectionContext.TrustServerCertificate = $true
$srv.ConnectionContext.EncryptConnection = $true

$db = $srv.Databases[$Database]
if ($null -eq $db) { throw "Database '$Database' not found on $Server" }

function New-Options([scriptblock] $configure) {
    $o = New-Object Microsoft.SqlServer.Management.Smo.ScriptingOptions
    $o.ScriptDrops = $false
    $o.IncludeIfNotExists = $false
    $o.SchemaQualify = $true
    $o.NoFileGroup = $true          # no "ON [PRIMARY]": the target database decides
    $o.NoCollation = $false         # keep each column's collation explicit
    $o.IncludeHeaders = $false      # no timestamp comments: the file must be diff-stable
    $o.DriIncludeSystemNames = $false
    $o.AnsiPadding = $false
    & $configure $o
    return $o
}

$tableOptions = New-Options {
    param($o)
    $o.DriPrimaryKey = $true
    $o.DriUniqueKeys = $true
    $o.DriChecks = $true
    $o.DriDefaults = $true
    $o.DriForeignKeys = $false
    $o.Indexes = $false
}
$indexOptions = New-Options {
    param($o)
    $o.DriPrimaryKey = $false
    $o.DriUniqueKeys = $false
    $o.Indexes = $true
    $o.ClusteredIndexes = $false
    $o.NonClusteredIndexes = $true
}
$fkOptions = New-Options {
    param($o)
    $o.DriForeignKeys = $true
    $o.DriAll = $false
    $o.DriForeignKeys = $true
}
$viewOptions = New-Options { param($o) }

function Join-Batches($statements) {
    # SMO returns SET statements and bodies as separate items; each becomes its own batch.
    return (($statements | ForEach-Object { $_.TrimEnd() }) -join "`r`nGO`r`n") + "`r`nGO`r`n"
}

$tables = $db.Tables | Where-Object { -not $_.IsSystemObject } | Sort-Object Name
$views = $db.Views | Where-Object { -not $_.IsSystemObject } | Sort-Object Name

$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("/* =====================================================================")
[void]$out.AppendLine("   $Title")
[void]$out.AppendLine("")
[void]$out.AppendLine("   The complete schema, scripted from a database that already had every")
[void]$out.AppendLine("   migration applied. Run it against an EMPTY database, created with")
[void]$out.AppendLine("   COLLATE Arabic_CI_AS:")
[void]$out.AppendLine("")
[void]$out.AppendLine("     sqlcmd -S <server> -d <database> -f 65001 -i baseline_through_V14.sql")
[void]$out.AppendLine("")
[void]$out.AppendLine("   Do NOT run V2 .. V14 on top of it: they are already part of this file.")
[void]$out.AppendLine("   New changes continue from V15. See ../README.md.")
[void]$out.AppendLine("")
[void]$out.AppendLine("   Generated by scripts/db/generate-baseline.ps1 - do not edit by hand;")
[void]$out.AppendLine("   scripts/db/compare-schemas.ps1 checks a database built from it against")
[void]$out.AppendLine("   the original.")
[void]$out.AppendLine("   ===================================================================== */")
[void]$out.AppendLine("")
[void]$out.AppendLine("SET ANSI_NULLS ON;")
[void]$out.AppendLine("GO")
[void]$out.AppendLine("SET QUOTED_IDENTIFIER ON;")
[void]$out.AppendLine("GO")
[void]$out.AppendLine("")

[void]$out.AppendLine("/* ---------------- tables ---------------- */")
[void]$out.AppendLine("GO")
foreach ($t in $tables) {
    $statements = $t.Script($tableOptions) | Where-Object { $_ -notmatch '^\s*SET (ANSI_NULLS|QUOTED_IDENTIFIER) (ON|OFF)\s*$' }
    [void]$out.Append((Join-Batches $statements))
    [void]$out.AppendLine("")
}

[void]$out.AppendLine("/* ---------------- indexes ---------------- */")
[void]$out.AppendLine("GO")
foreach ($t in $tables) {
    foreach ($i in ($t.Indexes | Sort-Object Name)) {
        # Indexes that back a primary key or unique constraint were scripted with the table.
        if ($i.IndexKeyType -ne [Microsoft.SqlServer.Management.Smo.IndexKeyType]::None) { continue }
        $statements = $i.Script($indexOptions) | Where-Object { $_ -notmatch '^\s*SET (ANSI_NULLS|QUOTED_IDENTIFIER) (ON|OFF)\s*$' }
        [void]$out.Append((Join-Batches $statements))
    }
}
[void]$out.AppendLine("")

[void]$out.AppendLine("/* ---------------- foreign keys ---------------- */")
[void]$out.AppendLine("GO")
foreach ($t in $tables) {
    foreach ($fk in ($t.ForeignKeys | Sort-Object Name)) {
        $statements = $fk.Script($fkOptions) | Where-Object { $_ -notmatch '^\s*SET (ANSI_NULLS|QUOTED_IDENTIFIER) (ON|OFF)\s*$' }
        [void]$out.Append((Join-Batches $statements))
    }
}
[void]$out.AppendLine("")

if ($views.Count -gt 0) {
    [void]$out.AppendLine("/* ---------------- views ---------------- */")
[void]$out.AppendLine("GO")
    foreach ($v in $views) {
        $statements = $v.Script($viewOptions) | Where-Object { $_ -notmatch '^\s*SET (ANSI_NULLS|QUOTED_IDENTIFIER) (ON|OFF)\s*$' }
        [void]$out.Append((Join-Batches $statements))
    }
}

$dir = Split-Path -Parent $Output
if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }
# UTF-8 with a BOM, not ASCII: a view's definition can carry non-ASCII text in a comment, and
# ASCII would silently turn it into '?'. Apply with:  sqlcmd -f 65001 ...
[System.IO.File]::WriteAllText($Output, $out.ToString(), (New-Object System.Text.UTF8Encoding($true)))

"Scripted $($tables.Count) tables and $($views.Count) view(s) from '$Database' into $Output"


