/* =====================================================================
   VELORA/ROYAL - baseline schema, through V14

   The complete schema, scripted from a database that already had every
   migration applied. Run it against an EMPTY database, created with
   COLLATE Arabic_CI_AS:

     sqlcmd -S <server> -d <database> -f 65001 -i baseline_through_V14.sql

   Do NOT run V2 .. V14 on top of it: they are already part of this file.
   New changes continue from V15. See ../README.md.

   Generated by scripts/db/generate-baseline.ps1 - do not edit by hand;
   scripts/db/compare-schemas.ps1 checks a database built from it against
   the original.
   ===================================================================== */

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

/* ---------------- tables ---------------- */
GO
CREATE TABLE [dbo].[app_user](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[email] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[phone_e164] [varchar](20) COLLATE Arabic_CI_AS NULL,
	[password_hash] [varchar](255) COLLATE Arabic_CI_AS NOT NULL,
	[first_name] [nvarchar](100) COLLATE Arabic_CI_AS NOT NULL,
	[last_name] [nvarchar](100) COLLATE Arabic_CI_AS NULL,
	[email_verified_at] [datetimeoffset](3) NULL,
	[phone_verified_at] [datetimeoffset](3) NULL,
	[preferred_locale] [varchar](5) COLLATE Arabic_CI_AS NOT NULL,
	[status] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[is_staff] [bit] NOT NULL,
	[last_login_at] [datetimeoffset](3) NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
	[updated_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_app_user] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[app_user] ADD  CONSTRAINT [df_user_locale]  DEFAULT ('ar') FOR [preferred_locale]
GO
ALTER TABLE [dbo].[app_user] ADD  CONSTRAINT [df_user_status]  DEFAULT ('ACTIVE') FOR [status]
GO
ALTER TABLE [dbo].[app_user] ADD  CONSTRAINT [df_user_staff]  DEFAULT ((0)) FOR [is_staff]
GO
ALTER TABLE [dbo].[app_user] ADD  CONSTRAINT [df_user_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO
ALTER TABLE [dbo].[app_user] ADD  CONSTRAINT [df_user_updated]  DEFAULT (sysdatetimeoffset()) FOR [updated_at]
GO
ALTER TABLE [dbo].[app_user]  WITH CHECK ADD  CONSTRAINT [ck_user_identifier] CHECK  (([email] IS NOT NULL OR [phone_e164] IS NOT NULL))
GO
ALTER TABLE [dbo].[app_user] CHECK CONSTRAINT [ck_user_identifier]
GO
ALTER TABLE [dbo].[app_user]  WITH CHECK ADD  CONSTRAINT [ck_user_status] CHECK  (([status]='DELETED' OR [status]='SUSPENDED' OR [status]='ACTIVE'))
GO
ALTER TABLE [dbo].[app_user] CHECK CONSTRAINT [ck_user_status]
GO

CREATE TABLE [dbo].[attribute](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[code] [varchar](50) COLLATE Arabic_CI_AS NOT NULL,
	[data_type] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[is_variant_defining] [bit] NOT NULL,
	[is_filterable] [bit] NOT NULL,
	[display_order] [smallint] NOT NULL,
 CONSTRAINT [pk_attribute] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_attr_code] UNIQUE NONCLUSTERED 
(
	[code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[attribute] ADD  CONSTRAINT [df_attr_type]  DEFAULT ('LIST') FOR [data_type]
GO
ALTER TABLE [dbo].[attribute] ADD  CONSTRAINT [df_attr_variant]  DEFAULT ((0)) FOR [is_variant_defining]
GO
ALTER TABLE [dbo].[attribute] ADD  CONSTRAINT [df_attr_filter]  DEFAULT ((1)) FOR [is_filterable]
GO
ALTER TABLE [dbo].[attribute] ADD  CONSTRAINT [df_attr_order]  DEFAULT ((0)) FOR [display_order]
GO
ALTER TABLE [dbo].[attribute]  WITH CHECK ADD  CONSTRAINT [ck_attr_type] CHECK  (([data_type]='BOOLEAN' OR [data_type]='NUMBER' OR [data_type]='TEXT' OR [data_type]='LIST'))
GO
ALTER TABLE [dbo].[attribute] CHECK CONSTRAINT [ck_attr_type]
GO

CREATE TABLE [dbo].[attribute_translation](
	[attribute_id] [bigint] NOT NULL,
	[locale] [varchar](5) COLLATE Arabic_CI_AS NOT NULL,
	[name] [nvarchar](150) COLLATE Arabic_CI_AS NOT NULL,
 CONSTRAINT [pk_attr_tr] PRIMARY KEY CLUSTERED 
(
	[attribute_id] ASC,
	[locale] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO

CREATE TABLE [dbo].[attribute_value](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[attribute_id] [bigint] NOT NULL,
	[code] [varchar](60) COLLATE Arabic_CI_AS NOT NULL,
	[hex_color] [varchar](7) COLLATE Arabic_CI_AS NULL,
	[display_order] [smallint] NOT NULL,
 CONSTRAINT [pk_attribute_value] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_av_code] UNIQUE NONCLUSTERED 
(
	[attribute_id] ASC,
	[code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[attribute_value] ADD  CONSTRAINT [df_av_order]  DEFAULT ((0)) FOR [display_order]
GO

CREATE TABLE [dbo].[attribute_value_translation](
	[attribute_value_id] [bigint] NOT NULL,
	[locale] [varchar](5) COLLATE Arabic_CI_AS NOT NULL,
	[name] [nvarchar](150) COLLATE Arabic_CI_AS NOT NULL,
 CONSTRAINT [pk_av_tr] PRIMARY KEY CLUSTERED 
(
	[attribute_value_id] ASC,
	[locale] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO

CREATE TABLE [dbo].[audit_log](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[action] [varchar](40) COLLATE Arabic_CI_AS NOT NULL,
	[entity_type] [varchar](40) COLLATE Arabic_CI_AS NOT NULL,
	[entity_id] [nvarchar](60) COLLATE Arabic_CI_AS NULL,
	[entity_label] [nvarchar](200) COLLATE Arabic_CI_AS NULL,
	[old_value] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
	[new_value] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
	[reason] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
	[actor_id] [bigint] NULL,
	[actor_name] [nvarchar](150) COLLATE Arabic_CI_AS NULL,
	[created_at] [datetimeoffset](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[audit_log] ADD  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO

CREATE TABLE [dbo].[back_in_stock_subscription](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[variant_id] [bigint] NOT NULL,
	[user_id] [bigint] NULL,
	[email] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[phone_e164] [varchar](20) COLLATE Arabic_CI_AS NULL,
	[notified_at] [datetimeoffset](3) NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_bis] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[back_in_stock_subscription] ADD  CONSTRAINT [df_bis_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO

CREATE TABLE [dbo].[brand](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[slug] [varchar](150) COLLATE Arabic_CI_AS NOT NULL,
	[name_ar] [nvarchar](150) COLLATE Arabic_CI_AS NOT NULL,
	[name_en] [nvarchar](150) COLLATE Arabic_CI_AS NOT NULL,
	[logo_url] [varchar](500) COLLATE Arabic_CI_AS NULL,
	[is_active] [bit] NOT NULL,
 CONSTRAINT [pk_brand] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_brand_slug] UNIQUE NONCLUSTERED 
(
	[slug] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[brand] ADD  CONSTRAINT [df_brand_active]  DEFAULT ((1)) FOR [is_active]
GO

CREATE TABLE [dbo].[cart](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[user_id] [bigint] NULL,
	[guest_token] [nvarchar](200) COLLATE Arabic_CI_AS NULL,
	[coupon_code] [varchar](50) COLLATE Arabic_CI_AS NULL,
	[status] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
	[updated_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_cart] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[cart] ADD  CONSTRAINT [df_cart_status]  DEFAULT ('ACTIVE') FOR [status]
GO
ALTER TABLE [dbo].[cart] ADD  CONSTRAINT [df_cart_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO
ALTER TABLE [dbo].[cart] ADD  CONSTRAINT [df_cart_updated]  DEFAULT (sysdatetimeoffset()) FOR [updated_at]
GO
ALTER TABLE [dbo].[cart]  WITH CHECK ADD  CONSTRAINT [ck_cart_owner] CHECK  (([user_id] IS NOT NULL OR [guest_token] IS NOT NULL))
GO
ALTER TABLE [dbo].[cart] CHECK CONSTRAINT [ck_cart_owner]
GO
ALTER TABLE [dbo].[cart]  WITH CHECK ADD  CONSTRAINT [ck_cart_status] CHECK  (([status]='ABANDONED' OR [status]='CONVERTED' OR [status]='MERGED' OR [status]='ACTIVE'))
GO
ALTER TABLE [dbo].[cart] CHECK CONSTRAINT [ck_cart_status]
GO

CREATE TABLE [dbo].[cart_item](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[cart_id] [bigint] NOT NULL,
	[variant_id] [bigint] NOT NULL,
	[quantity] [int] NOT NULL,
	[price_at_add] [decimal](19, 4) NOT NULL,
	[added_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_cart_item] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_cart_variant] UNIQUE NONCLUSTERED 
(
	[cart_id] ASC,
	[variant_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[cart_item] ADD  CONSTRAINT [df_ci_added]  DEFAULT (sysdatetimeoffset()) FOR [added_at]
GO
ALTER TABLE [dbo].[cart_item]  WITH CHECK ADD  CONSTRAINT [ck_ci_qty] CHECK  (([quantity]>(0)))
GO
ALTER TABLE [dbo].[cart_item] CHECK CONSTRAINT [ck_ci_qty]
GO

CREATE TABLE [dbo].[category](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[parent_id] [bigint] NULL,
	[slug] [varchar](150) COLLATE Arabic_CI_AS NOT NULL,
	[image_url] [varchar](500) COLLATE Arabic_CI_AS NULL,
	[banner_url] [varchar](500) COLLATE Arabic_CI_AS NULL,
	[display_order] [smallint] NOT NULL,
	[is_active] [bit] NOT NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_category] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_cat_slug] UNIQUE NONCLUSTERED 
(
	[slug] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[category] ADD  CONSTRAINT [df_cat_order]  DEFAULT ((0)) FOR [display_order]
GO
ALTER TABLE [dbo].[category] ADD  CONSTRAINT [df_cat_active]  DEFAULT ((1)) FOR [is_active]
GO
ALTER TABLE [dbo].[category] ADD  CONSTRAINT [df_cat_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO

CREATE TABLE [dbo].[category_attribute](
	[category_id] [bigint] NOT NULL,
	[attribute_id] [bigint] NOT NULL,
	[is_required] [bit] NOT NULL,
	[display_order] [smallint] NOT NULL,
 CONSTRAINT [pk_category_attribute] PRIMARY KEY CLUSTERED 
(
	[category_id] ASC,
	[attribute_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[category_attribute] ADD  CONSTRAINT [df_ca_required]  DEFAULT ((0)) FOR [is_required]
GO
ALTER TABLE [dbo].[category_attribute] ADD  CONSTRAINT [df_ca_order]  DEFAULT ((0)) FOR [display_order]
GO

CREATE TABLE [dbo].[category_translation](
	[category_id] [bigint] NOT NULL,
	[locale] [varchar](5) COLLATE Arabic_CI_AS NOT NULL,
	[name] [nvarchar](150) COLLATE Arabic_CI_AS NOT NULL,
	[description] [nvarchar](max) COLLATE Arabic_CI_AS NULL,
	[meta_title] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[meta_description] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
 CONSTRAINT [pk_cat_tr] PRIMARY KEY CLUSTERED 
(
	[category_id] ASC,
	[locale] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO

CREATE TABLE [dbo].[city](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[governorate_id] [bigint] NOT NULL,
	[name_ar] [nvarchar](120) COLLATE Arabic_CI_AS NOT NULL,
	[name_en] [nvarchar](120) COLLATE Arabic_CI_AS NOT NULL,
	[is_active] [bit] NOT NULL,
 CONSTRAINT [pk_city] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_city_name] UNIQUE NONCLUSTERED 
(
	[governorate_id] ASC,
	[name_en] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[city] ADD  CONSTRAINT [df_city_active]  DEFAULT ((1)) FOR [is_active]
GO

CREATE TABLE [dbo].[cod_remittance](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[reference] [nvarchar](40) COLLATE Arabic_CI_AS NOT NULL,
	[courier_name] [nvarchar](150) COLLATE Arabic_CI_AS NOT NULL,
	[courier_reference] [nvarchar](100) COLLATE Arabic_CI_AS NULL,
	[settlement_date] [date] NOT NULL,
	[status] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[expected_amount] [decimal](19, 4) NOT NULL,
	[received_amount] [decimal](19, 4) NOT NULL,
	[difference] [decimal](19, 4) NOT NULL,
	[order_count] [int] NOT NULL,
	[note] [nvarchar](1000) COLLATE Arabic_CI_AS NULL,
	[recorded_by] [bigint] NULL,
	[created_at] [datetimeoffset](7) NOT NULL,
	[cancelled_at] [datetimeoffset](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[cod_remittance] ADD  DEFAULT ('SETTLED') FOR [status]
GO
ALTER TABLE [dbo].[cod_remittance] ADD  DEFAULT ((0)) FOR [difference]
GO
ALTER TABLE [dbo].[cod_remittance] ADD  DEFAULT ((0)) FOR [order_count]
GO
ALTER TABLE [dbo].[cod_remittance] ADD  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO
ALTER TABLE [dbo].[cod_remittance]  WITH CHECK ADD  CONSTRAINT [ck_remittance_status] CHECK  (([status]='CANCELLED' OR [status]='SHORT' OR [status]='SETTLED'))
GO
ALTER TABLE [dbo].[cod_remittance] CHECK CONSTRAINT [ck_remittance_status]
GO

CREATE TABLE [dbo].[cod_remittance_item](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[remittance_id] [bigint] NOT NULL,
	[order_id] [bigint] NOT NULL,
	[order_number] [nvarchar](30) COLLATE Arabic_CI_AS NOT NULL,
	[amount] [decimal](19, 4) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO

CREATE TABLE [dbo].[credit_note](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[invoice_id] [bigint] NOT NULL,
	[credit_note_number] [varchar](30) COLLATE Arabic_CI_AS NOT NULL,
	[amount] [decimal](19, 4) NOT NULL,
	[reason] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[issued_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_credit_note] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_cn_number] UNIQUE NONCLUSTERED 
(
	[credit_note_number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[credit_note] ADD  CONSTRAINT [df_cn_issued]  DEFAULT (sysdatetimeoffset()) FOR [issued_at]
GO

CREATE TABLE [dbo].[custom_order_request](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[request_number] [varchar](30) COLLATE Arabic_CI_AS NOT NULL,
	[fiscal_year] [int] NOT NULL,
	[sequence_number] [int] NOT NULL,
	[type] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[status] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[product_id] [bigint] NULL,
	[customer_id] [bigint] NULL,
	[contact_name] [nvarchar](150) COLLATE Arabic_CI_AS NOT NULL,
	[phone] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[alt_phone] [varchar](20) COLLATE Arabic_CI_AS NULL,
	[email] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[governorate_id] [bigint] NOT NULL,
	[area] [nvarchar](150) COLLATE Arabic_CI_AS NULL,
	[street_address] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[width_cm] [decimal](8, 2) NULL,
	[height_cm] [decimal](8, 2) NULL,
	[depth_cm] [decimal](8, 2) NULL,
	[quantity] [int] NOT NULL,
	[notes] [nvarchar](1000) COLLATE Arabic_CI_AS NULL,
	[quoted_amount] [decimal](19, 4) NULL,
	[admin_note] [nvarchar](1000) COLLATE Arabic_CI_AS NULL,
	[converted_order_id] [bigint] NULL,
	[created_at] [datetimeoffset](7) NOT NULL,
	[updated_at] [datetimeoffset](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[custom_order_request] ADD  DEFAULT ('NEW') FOR [status]
GO
ALTER TABLE [dbo].[custom_order_request] ADD  DEFAULT ((1)) FOR [quantity]
GO
ALTER TABLE [dbo].[custom_order_request] ADD  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO
ALTER TABLE [dbo].[custom_order_request] ADD  DEFAULT (sysdatetimeoffset()) FOR [updated_at]
GO
ALTER TABLE [dbo].[custom_order_request]  WITH CHECK ADD  CONSTRAINT [ck_custom_req_quantity] CHECK  (([quantity]>=(1)))
GO
ALTER TABLE [dbo].[custom_order_request] CHECK CONSTRAINT [ck_custom_req_quantity]
GO
ALTER TABLE [dbo].[custom_order_request]  WITH CHECK ADD  CONSTRAINT [ck_custom_req_quote] CHECK  (([quoted_amount] IS NULL OR [quoted_amount]>(0)))
GO
ALTER TABLE [dbo].[custom_order_request] CHECK CONSTRAINT [ck_custom_req_quote]
GO
ALTER TABLE [dbo].[custom_order_request]  WITH CHECK ADD  CONSTRAINT [ck_custom_req_status] CHECK  (([status]='CONVERTED' OR [status]='REJECTED' OR [status]='ACCEPTED' OR [status]='QUOTED' OR [status]='CONTACTED' OR [status]='NEW'))
GO
ALTER TABLE [dbo].[custom_order_request] CHECK CONSTRAINT [ck_custom_req_status]
GO
ALTER TABLE [dbo].[custom_order_request]  WITH CHECK ADD  CONSTRAINT [ck_custom_req_type] CHECK  (([type]='CUSTOM_WORK' OR [type]='MADE_TO_ORDER' OR [type]='SIZE_VARIANT'))
GO
ALTER TABLE [dbo].[custom_order_request] CHECK CONSTRAINT [ck_custom_req_type]
GO

CREATE TABLE [dbo].[custom_order_request_attachment](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[request_id] [bigint] NOT NULL,
	[storage_key] [nvarchar](500) COLLATE Arabic_CI_AS NOT NULL,
	[content_type] [varchar](50) COLLATE Arabic_CI_AS NOT NULL,
	[size_bytes] [bigint] NOT NULL,
	[created_at] [datetimeoffset](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[custom_order_request_attachment] ADD  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO

CREATE TABLE [dbo].[custom_order_request_sequence](
	[fiscal_year] [int] NOT NULL,
	[last_number] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[fiscal_year] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[custom_order_request_sequence] ADD  DEFAULT ((0)) FOR [last_number]
GO
ALTER TABLE [dbo].[custom_order_request_sequence]  WITH CHECK ADD  CONSTRAINT [ck_custom_req_seq_positive] CHECK  (([last_number]>=(0)))
GO
ALTER TABLE [dbo].[custom_order_request_sequence] CHECK CONSTRAINT [ck_custom_req_seq_positive]
GO

CREATE TABLE [dbo].[customer_address](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[user_id] [bigint] NOT NULL,
	[label] [nvarchar](30) COLLATE Arabic_CI_AS NULL,
	[recipient_name] [nvarchar](150) COLLATE Arabic_CI_AS NOT NULL,
	[phone_e164] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[alt_phone_e164] [varchar](20) COLLATE Arabic_CI_AS NULL,
	[governorate_id] [bigint] NOT NULL,
	[city_id] [bigint] NULL,
	[area] [nvarchar](150) COLLATE Arabic_CI_AS NULL,
	[street_address] [nvarchar](255) COLLATE Arabic_CI_AS NOT NULL,
	[building] [nvarchar](50) COLLATE Arabic_CI_AS NULL,
	[floor] [nvarchar](20) COLLATE Arabic_CI_AS NULL,
	[apartment] [nvarchar](20) COLLATE Arabic_CI_AS NULL,
	[landmark] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[latitude] [decimal](10, 7) NULL,
	[longitude] [decimal](10, 7) NULL,
	[is_default] [bit] NOT NULL,
	[deleted_at] [datetimeoffset](3) NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_customer_address] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[customer_address] ADD  CONSTRAINT [df_addr_default]  DEFAULT ((0)) FOR [is_default]
GO
ALTER TABLE [dbo].[customer_address] ADD  CONSTRAINT [df_addr_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO

CREATE TABLE [dbo].[customer_order](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[order_number] [varchar](30) COLLATE Arabic_CI_AS NOT NULL,
	[customer_id] [bigint] NULL,
	[fulfillment_status] [varchar](30) COLLATE Arabic_CI_AS NOT NULL,
	[payment_status] [varchar](30) COLLATE Arabic_CI_AS NOT NULL,
	[payment_method] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[currency] [char](3) COLLATE Arabic_CI_AS NOT NULL,
	[subtotal_gross] [decimal](19, 4) NOT NULL,
	[discount_total] [decimal](19, 4) NOT NULL,
	[shipping_cost] [decimal](19, 4) NOT NULL,
	[cod_fee] [decimal](19, 4) NOT NULL,
	[grand_total] [decimal](19, 4) NOT NULL,
	[tax_total] [decimal](19, 4) NOT NULL,
	[net_total] [decimal](19, 4) NOT NULL,
	[contact_name] [nvarchar](150) COLLATE Arabic_CI_AS NOT NULL,
	[contact_phone] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[contact_alt_phone] [varchar](20) COLLATE Arabic_CI_AS NULL,
	[contact_email] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[ship_governorate_id] [bigint] NULL,
	[ship_governorate_name] [nvarchar](100) COLLATE Arabic_CI_AS NOT NULL,
	[ship_city_name] [nvarchar](120) COLLATE Arabic_CI_AS NOT NULL,
	[ship_area] [nvarchar](150) COLLATE Arabic_CI_AS NULL,
	[ship_street_address] [nvarchar](255) COLLATE Arabic_CI_AS NOT NULL,
	[ship_building] [nvarchar](50) COLLATE Arabic_CI_AS NULL,
	[ship_floor] [nvarchar](20) COLLATE Arabic_CI_AS NULL,
	[ship_apartment] [nvarchar](20) COLLATE Arabic_CI_AS NULL,
	[ship_landmark] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[shipping_zone_name] [nvarchar](100) COLLATE Arabic_CI_AS NULL,
	[delivery_days_min] [smallint] NULL,
	[delivery_days_max] [smallint] NULL,
	[customer_note] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
	[internal_note] [nvarchar](1000) COLLATE Arabic_CI_AS NULL,
	[locale] [varchar](5) COLLATE Arabic_CI_AS NOT NULL,
	[placed_at] [datetimeoffset](3) NOT NULL,
	[confirmed_at] [datetimeoffset](3) NULL,
	[shipped_at] [datetimeoffset](3) NULL,
	[delivered_at] [datetimeoffset](3) NULL,
	[cancelled_at] [datetimeoffset](3) NULL,
	[cancel_reason] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[updated_at] [datetimeoffset](3) NOT NULL,
	[shipping_breakdown] [varchar](500) COLLATE Arabic_CI_AS NULL,
	[shipping_cap_applied] [bit] NULL,
	[shipping_uncapped_cost] [decimal](19, 4) NULL,
 CONSTRAINT [pk_customer_order] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_order_number] UNIQUE NONCLUSTERED 
(
	[order_number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[customer_order] ADD  CONSTRAINT [df_ord_fulfil]  DEFAULT ('PENDING') FOR [fulfillment_status]
GO
ALTER TABLE [dbo].[customer_order] ADD  CONSTRAINT [df_ord_pay]  DEFAULT ('PENDING') FOR [payment_status]
GO
ALTER TABLE [dbo].[customer_order] ADD  CONSTRAINT [df_ord_method]  DEFAULT ('COD') FOR [payment_method]
GO
ALTER TABLE [dbo].[customer_order] ADD  CONSTRAINT [df_ord_ccy]  DEFAULT ('EGP') FOR [currency]
GO
ALTER TABLE [dbo].[customer_order] ADD  CONSTRAINT [df_ord_disc]  DEFAULT ((0)) FOR [discount_total]
GO
ALTER TABLE [dbo].[customer_order] ADD  CONSTRAINT [df_ord_ship]  DEFAULT ((0)) FOR [shipping_cost]
GO
ALTER TABLE [dbo].[customer_order] ADD  CONSTRAINT [df_ord_cod]  DEFAULT ((0)) FOR [cod_fee]
GO
ALTER TABLE [dbo].[customer_order] ADD  CONSTRAINT [df_ord_locale]  DEFAULT ('ar') FOR [locale]
GO
ALTER TABLE [dbo].[customer_order] ADD  CONSTRAINT [df_ord_placed]  DEFAULT (sysdatetimeoffset()) FOR [placed_at]
GO
ALTER TABLE [dbo].[customer_order] ADD  CONSTRAINT [df_ord_updated]  DEFAULT (sysdatetimeoffset()) FOR [updated_at]
GO
ALTER TABLE [dbo].[customer_order]  WITH CHECK ADD  CONSTRAINT [ck_ord_fulfillment] CHECK  (([fulfillment_status]='PARTIALLY_RETURNED' OR [fulfillment_status]='RETURNED' OR [fulfillment_status]='CANCELLED' OR [fulfillment_status]='RETURNED_TO_SELLER' OR [fulfillment_status]='REFUSED_ON_DELIVERY' OR [fulfillment_status]='DELIVERY_FAILED' OR [fulfillment_status]='DELIVERED' OR [fulfillment_status]='OUT_FOR_DELIVERY' OR [fulfillment_status]='SHIPPED' OR [fulfillment_status]='PROCESSING' OR [fulfillment_status]='CONFIRMED' OR [fulfillment_status]='PENDING'))
GO
ALTER TABLE [dbo].[customer_order] CHECK CONSTRAINT [ck_ord_fulfillment]
GO
ALTER TABLE [dbo].[customer_order]  WITH CHECK ADD  CONSTRAINT [ck_ord_payment] CHECK  (([payment_status]='EXPIRED' OR [payment_status]='FAILED' OR [payment_status]='REFUNDED' OR [payment_status]='PARTIALLY_REFUNDED' OR [payment_status]='PAID' OR [payment_status]='AUTHORIZED' OR [payment_status]='PENDING'))
GO
ALTER TABLE [dbo].[customer_order] CHECK CONSTRAINT [ck_ord_payment]
GO
ALTER TABLE [dbo].[customer_order]  WITH CHECK ADD  CONSTRAINT [ck_ord_total] CHECK  (([grand_total]>=(0)))
GO
ALTER TABLE [dbo].[customer_order] CHECK CONSTRAINT [ck_ord_total]
GO

CREATE TABLE [dbo].[governorate](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[code] [varchar](10) COLLATE Arabic_CI_AS NOT NULL,
	[name_ar] [nvarchar](100) COLLATE Arabic_CI_AS NOT NULL,
	[name_en] [nvarchar](100) COLLATE Arabic_CI_AS NOT NULL,
	[is_active] [bit] NOT NULL,
	[display_order] [smallint] NOT NULL,
 CONSTRAINT [pk_governorate] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_gov_code] UNIQUE NONCLUSTERED 
(
	[code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[governorate] ADD  CONSTRAINT [df_gov_active]  DEFAULT ((1)) FOR [is_active]
GO
ALTER TABLE [dbo].[governorate] ADD  CONSTRAINT [df_gov_order]  DEFAULT ((0)) FOR [display_order]
GO

CREATE TABLE [dbo].[idempotency_key](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[idempotency_key] [nvarchar](100) COLLATE Arabic_CI_AS NOT NULL,
	[endpoint] [nvarchar](200) COLLATE Arabic_CI_AS NOT NULL,
	[request_hash] [varchar](64) COLLATE Arabic_CI_AS NULL,
	[status] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[response_body] [nvarchar](max) COLLATE Arabic_CI_AS NULL,
	[response_status] [int] NULL,
	[user_id] [bigint] NULL,
	[created_at] [datetimeoffset](7) NOT NULL,
	[completed_at] [datetimeoffset](7) NULL,
	[expires_at] [datetimeoffset](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[idempotency_key] ADD  DEFAULT ('IN_PROGRESS') FOR [status]
GO
ALTER TABLE [dbo].[idempotency_key] ADD  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO
ALTER TABLE [dbo].[idempotency_key]  WITH CHECK ADD  CONSTRAINT [ck_idem_status] CHECK  (([status]='FAILED' OR [status]='COMPLETED' OR [status]='IN_PROGRESS'))
GO
ALTER TABLE [dbo].[idempotency_key] CHECK CONSTRAINT [ck_idem_status]
GO

CREATE TABLE [dbo].[inventory](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[variant_id] [bigint] NOT NULL,
	[location_code] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[qty_on_hand] [int] NOT NULL,
	[qty_reserved] [int] NOT NULL,
	[min_stock_level] [int] NOT NULL,
	[version] [bigint] NOT NULL,
	[updated_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_inventory] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[inventory] ADD  CONSTRAINT [df_inv_loc]  DEFAULT ('MAIN') FOR [location_code]
GO
ALTER TABLE [dbo].[inventory] ADD  CONSTRAINT [df_inv_onhand]  DEFAULT ((0)) FOR [qty_on_hand]
GO
ALTER TABLE [dbo].[inventory] ADD  CONSTRAINT [df_inv_reserved]  DEFAULT ((0)) FOR [qty_reserved]
GO
ALTER TABLE [dbo].[inventory] ADD  CONSTRAINT [df_inv_min]  DEFAULT ((3)) FOR [min_stock_level]
GO
ALTER TABLE [dbo].[inventory] ADD  CONSTRAINT [df_inv_version]  DEFAULT ((0)) FOR [version]
GO
ALTER TABLE [dbo].[inventory] ADD  CONSTRAINT [df_inv_updated]  DEFAULT (sysdatetimeoffset()) FOR [updated_at]
GO
ALTER TABLE [dbo].[inventory]  WITH CHECK ADD  CONSTRAINT [ck_inv_balance] CHECK  (([qty_reserved]<=[qty_on_hand]))
GO
ALTER TABLE [dbo].[inventory] CHECK CONSTRAINT [ck_inv_balance]
GO
ALTER TABLE [dbo].[inventory]  WITH CHECK ADD  CONSTRAINT [ck_inv_onhand] CHECK  (([qty_on_hand]>=(0)))
GO
ALTER TABLE [dbo].[inventory] CHECK CONSTRAINT [ck_inv_onhand]
GO
ALTER TABLE [dbo].[inventory]  WITH CHECK ADD  CONSTRAINT [ck_inv_reserved] CHECK  (([qty_reserved]>=(0)))
GO
ALTER TABLE [dbo].[inventory] CHECK CONSTRAINT [ck_inv_reserved]
GO

CREATE TABLE [dbo].[invoice](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[invoice_number] [nvarchar](40) COLLATE Arabic_CI_AS NOT NULL,
	[fiscal_year] [int] NOT NULL,
	[sequence_number] [int] NOT NULL,
	[order_id] [bigint] NOT NULL,
	[status] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[seller_name] [nvarchar](200) COLLATE Arabic_CI_AS NOT NULL,
	[seller_address] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
	[seller_phone] [nvarchar](30) COLLATE Arabic_CI_AS NULL,
	[seller_email] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[seller_tax_number] [nvarchar](30) COLLATE Arabic_CI_AS NULL,
	[seller_commercial_register] [nvarchar](30) COLLATE Arabic_CI_AS NULL,
	[buyer_name] [nvarchar](150) COLLATE Arabic_CI_AS NOT NULL,
	[buyer_phone] [nvarchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[buyer_address] [nvarchar](800) COLLATE Arabic_CI_AS NULL,
	[currency] [char](3) COLLATE Arabic_CI_AS NOT NULL,
	[subtotal_gross] [decimal](19, 4) NOT NULL,
	[discount_total] [decimal](19, 4) NOT NULL,
	[shipping_cost] [decimal](19, 4) NOT NULL,
	[grand_total] [decimal](19, 4) NOT NULL,
	[tax_total] [decimal](19, 4) NOT NULL,
	[net_total] [decimal](19, 4) NOT NULL,
	[payment_method] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[pdf_key] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
	[issued_at] [datetimeoffset](7) NOT NULL,
	[cancelled_at] [datetimeoffset](7) NULL,
	[cancel_reason] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[invoice] ADD  DEFAULT ('ISSUED') FOR [status]
GO
ALTER TABLE [dbo].[invoice] ADD  DEFAULT ('EGP') FOR [currency]
GO
ALTER TABLE [dbo].[invoice] ADD  DEFAULT ((0)) FOR [discount_total]
GO
ALTER TABLE [dbo].[invoice] ADD  DEFAULT ((0)) FOR [shipping_cost]
GO
ALTER TABLE [dbo].[invoice] ADD  DEFAULT (sysdatetimeoffset()) FOR [issued_at]
GO
ALTER TABLE [dbo].[invoice]  WITH CHECK ADD  CONSTRAINT [ck_invoice_status] CHECK  (([status]='CANCELLED' OR [status]='ISSUED'))
GO
ALTER TABLE [dbo].[invoice] CHECK CONSTRAINT [ck_invoice_status]
GO

CREATE TABLE [dbo].[invoice_sequence](
	[fiscal_year] [int] NOT NULL,
	[last_number] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[fiscal_year] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[invoice_sequence] ADD  DEFAULT ((0)) FOR [last_number]
GO
ALTER TABLE [dbo].[invoice_sequence]  WITH CHECK ADD  CONSTRAINT [ck_invoice_seq_positive] CHECK  (([last_number]>=(0)))
GO
ALTER TABLE [dbo].[invoice_sequence] CHECK CONSTRAINT [ck_invoice_seq_positive]
GO

CREATE TABLE [dbo].[notification_log](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[template_code] [varchar](60) COLLATE Arabic_CI_AS NULL,
	[channel] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[recipient] [nvarchar](255) COLLATE Arabic_CI_AS NOT NULL,
	[order_id] [bigint] NULL,
	[status] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[provider_response] [nvarchar](max) COLLATE Arabic_CI_AS NULL,
	[sent_at] [datetimeoffset](3) NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_notification_log] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[notification_log] ADD  CONSTRAINT [df_nl_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO

CREATE TABLE [dbo].[notification_template](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[code] [varchar](60) COLLATE Arabic_CI_AS NOT NULL,
	[channel] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[locale] [varchar](5) COLLATE Arabic_CI_AS NOT NULL,
	[subject] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[body] [nvarchar](max) COLLATE Arabic_CI_AS NOT NULL,
	[is_active] [bit] NOT NULL,
 CONSTRAINT [pk_notification_template] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_nt] UNIQUE NONCLUSTERED 
(
	[code] ASC,
	[channel] ASC,
	[locale] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[notification_template] ADD  CONSTRAINT [df_nt_active]  DEFAULT ((1)) FOR [is_active]
GO

CREATE TABLE [dbo].[order_item](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[order_id] [bigint] NOT NULL,
	[variant_id] [bigint] NULL,
	[product_id] [bigint] NULL,
	[product_name_ar] [nvarchar](255) COLLATE Arabic_CI_AS NOT NULL,
	[product_name_en] [nvarchar](255) COLLATE Arabic_CI_AS NOT NULL,
	[sku] [varchar](60) COLLATE Arabic_CI_AS NOT NULL,
	[variant_summary] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[image_url] [varchar](500) COLLATE Arabic_CI_AS NULL,
	[unit_price_gross] [decimal](19, 4) NOT NULL,
	[quantity] [int] NOT NULL,
	[line_discount] [decimal](19, 4) NOT NULL,
	[allocated_cart_discount] [decimal](19, 4) NOT NULL,
	[tax_rate] [decimal](5, 4) NOT NULL,
	[line_total_gross] [decimal](19, 4) NOT NULL,
	[line_tax_amount] [decimal](19, 4) NOT NULL,
	[quantity_returned] [int] NOT NULL,
 CONSTRAINT [pk_order_item] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[order_item] ADD  CONSTRAINT [df_oi_disc]  DEFAULT ((0)) FOR [line_discount]
GO
ALTER TABLE [dbo].[order_item] ADD  CONSTRAINT [df_oi_alloc]  DEFAULT ((0)) FOR [allocated_cart_discount]
GO
ALTER TABLE [dbo].[order_item] ADD  CONSTRAINT [df_oi_ret]  DEFAULT ((0)) FOR [quantity_returned]
GO
ALTER TABLE [dbo].[order_item]  WITH CHECK ADD  CONSTRAINT [ck_oi_qty] CHECK  (([quantity]>(0)))
GO
ALTER TABLE [dbo].[order_item] CHECK CONSTRAINT [ck_oi_qty]
GO
ALTER TABLE [dbo].[order_item]  WITH CHECK ADD  CONSTRAINT [ck_oi_returned] CHECK  (([quantity_returned]<=[quantity]))
GO
ALTER TABLE [dbo].[order_item] CHECK CONSTRAINT [ck_oi_returned]
GO

CREATE TABLE [dbo].[order_status_history](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[order_id] [bigint] NOT NULL,
	[status_kind] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[from_status] [varchar](30) COLLATE Arabic_CI_AS NULL,
	[to_status] [varchar](30) COLLATE Arabic_CI_AS NOT NULL,
	[note] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
	[actor_id] [bigint] NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_order_status_history] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[order_status_history] ADD  CONSTRAINT [df_osh_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO
ALTER TABLE [dbo].[order_status_history]  WITH CHECK ADD  CONSTRAINT [ck_osh_kind] CHECK  (([status_kind]='PAYMENT' OR [status_kind]='FULFILLMENT'))
GO
ALTER TABLE [dbo].[order_status_history] CHECK CONSTRAINT [ck_osh_kind]
GO

CREATE TABLE [dbo].[otp_verification](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[user_id] [bigint] NULL,
	[destination] [nvarchar](255) COLLATE Arabic_CI_AS NOT NULL,
	[channel] [varchar](10) COLLATE Arabic_CI_AS NOT NULL,
	[purpose] [varchar](30) COLLATE Arabic_CI_AS NOT NULL,
	[code_hash] [varchar](255) COLLATE Arabic_CI_AS NOT NULL,
	[attempts] [smallint] NOT NULL,
	[expires_at] [datetimeoffset](3) NOT NULL,
	[consumed_at] [datetimeoffset](3) NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_otp] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[otp_verification] ADD  CONSTRAINT [df_otp_attempts]  DEFAULT ((0)) FOR [attempts]
GO
ALTER TABLE [dbo].[otp_verification] ADD  CONSTRAINT [df_otp_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO

CREATE TABLE [dbo].[password_reset_token](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[user_id] [bigint] NOT NULL,
	[token_hash] [varchar](255) COLLATE Arabic_CI_AS NOT NULL,
	[expires_at] [datetimeoffset](3) NOT NULL,
	[used_at] [datetimeoffset](3) NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_prt] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_prt_hash] UNIQUE NONCLUSTERED 
(
	[token_hash] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[password_reset_token] ADD  CONSTRAINT [df_prt_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO

CREATE TABLE [dbo].[payment_transaction](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[order_id] [bigint] NOT NULL,
	[method] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[provider] [varchar](40) COLLATE Arabic_CI_AS NULL,
	[provider_reference] [varchar](120) COLLATE Arabic_CI_AS NULL,
	[idempotency_key] [varchar](120) COLLATE Arabic_CI_AS NULL,
	[amount] [decimal](19, 4) NOT NULL,
	[currency] [char](3) COLLATE Arabic_CI_AS NOT NULL,
	[status] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[raw_payload] [nvarchar](max) COLLATE Arabic_CI_AS NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_payment_transaction] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[payment_transaction] ADD  CONSTRAINT [df_pt_ccy]  DEFAULT ('EGP') FOR [currency]
GO
ALTER TABLE [dbo].[payment_transaction] ADD  CONSTRAINT [df_pt_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO

CREATE TABLE [dbo].[permission](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[code] [varchar](80) COLLATE Arabic_CI_AS NOT NULL,
	[module] [varchar](40) COLLATE Arabic_CI_AS NOT NULL,
	[description] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
 CONSTRAINT [pk_permission] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_permission_code] UNIQUE NONCLUSTERED 
(
	[code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO

CREATE TABLE [dbo].[product](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[brand_id] [bigint] NULL,
	[category_id] [bigint] NOT NULL,
	[slug] [varchar](200) COLLATE Arabic_CI_AS NOT NULL,
	[status] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[is_featured] [bit] NOT NULL,
	[is_new_arrival] [bit] NOT NULL,
	[published_at] [datetimeoffset](3) NULL,
	[archived_at] [datetimeoffset](3) NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
	[updated_at] [datetimeoffset](3) NOT NULL,
	[fulfillment_type] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[shipping_size_class] [varchar](10) COLLATE Arabic_CI_AS NULL,
 CONSTRAINT [pk_product] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_prod_slug] UNIQUE NONCLUSTERED 
(
	[slug] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[product] ADD  CONSTRAINT [df_prod_status]  DEFAULT ('DRAFT') FOR [status]
GO
ALTER TABLE [dbo].[product] ADD  CONSTRAINT [df_prod_feat]  DEFAULT ((0)) FOR [is_featured]
GO
ALTER TABLE [dbo].[product] ADD  CONSTRAINT [df_prod_new]  DEFAULT ((0)) FOR [is_new_arrival]
GO
ALTER TABLE [dbo].[product] ADD  CONSTRAINT [df_prod_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO
ALTER TABLE [dbo].[product] ADD  CONSTRAINT [df_prod_updated]  DEFAULT (sysdatetimeoffset()) FOR [updated_at]
GO
ALTER TABLE [dbo].[product] ADD  CONSTRAINT [DF_product_fulfillment_type]  DEFAULT ('READY_MADE') FOR [fulfillment_type]
GO
ALTER TABLE [dbo].[product]  WITH CHECK ADD  CONSTRAINT [ck_prod_status] CHECK  (([status]='ARCHIVED' OR [status]='ACTIVE' OR [status]='DRAFT'))
GO
ALTER TABLE [dbo].[product] CHECK CONSTRAINT [ck_prod_status]
GO
ALTER TABLE [dbo].[product]  WITH CHECK ADD  CONSTRAINT [CK_product_fulfillment_type] CHECK  (([fulfillment_type]='CUSTOM_WORK' OR [fulfillment_type]='MADE_TO_ORDER' OR [fulfillment_type]='READY_MADE'))
GO
ALTER TABLE [dbo].[product] CHECK CONSTRAINT [CK_product_fulfillment_type]
GO
ALTER TABLE [dbo].[product]  WITH CHECK ADD  CONSTRAINT [CK_product_shipping_size_class] CHECK  (([shipping_size_class] IS NULL OR ([shipping_size_class]='LARGE' OR [shipping_size_class]='MEDIUM' OR [shipping_size_class]='SMALL')))
GO
ALTER TABLE [dbo].[product] CHECK CONSTRAINT [CK_product_shipping_size_class]
GO

CREATE TABLE [dbo].[product_attribute_value](
	[product_id] [bigint] NOT NULL,
	[attribute_id] [bigint] NOT NULL,
	[attribute_value_id] [bigint] NULL,
	[value_text] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
 CONSTRAINT [pk_pav] PRIMARY KEY CLUSTERED 
(
	[product_id] ASC,
	[attribute_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO

CREATE TABLE [dbo].[product_image](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[product_id] [bigint] NOT NULL,
	[variant_id] [bigint] NULL,
	[url] [varchar](500) COLLATE Arabic_CI_AS NOT NULL,
	[thumb_url] [varchar](500) COLLATE Arabic_CI_AS NULL,
	[alt_text_ar] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[alt_text_en] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[is_main] [bit] NOT NULL,
	[display_order] [smallint] NOT NULL,
 CONSTRAINT [pk_product_image] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[product_image] ADD  CONSTRAINT [df_img_main]  DEFAULT ((0)) FOR [is_main]
GO
ALTER TABLE [dbo].[product_image] ADD  CONSTRAINT [df_img_order]  DEFAULT ((0)) FOR [display_order]
GO

CREATE TABLE [dbo].[product_translation](
	[product_id] [bigint] NOT NULL,
	[locale] [varchar](5) COLLATE Arabic_CI_AS NOT NULL,
	[name] [nvarchar](255) COLLATE Arabic_CI_AS NOT NULL,
	[short_description] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
	[description] [nvarchar](max) COLLATE Arabic_CI_AS NULL,
	[meta_title] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[meta_description] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
	[search_text] [nvarchar](1000) COLLATE Arabic_CI_AS NULL,
 CONSTRAINT [pk_prod_tr] PRIMARY KEY CLUSTERED 
(
	[product_id] ASC,
	[locale] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO

CREATE TABLE [dbo].[product_variant](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[product_id] [bigint] NOT NULL,
	[sku] [varchar](60) COLLATE Arabic_CI_AS NOT NULL,
	[barcode] [varchar](60) COLLATE Arabic_CI_AS NULL,
	[price] [decimal](19, 4) NOT NULL,
	[compare_at_price] [decimal](19, 4) NULL,
	[cost_price] [decimal](19, 4) NULL,
	[tax_rate] [decimal](5, 4) NOT NULL,
	[weight_grams] [int] NOT NULL,
	[length_mm] [int] NULL,
	[width_mm] [int] NULL,
	[height_mm] [int] NULL,
	[position] [smallint] NOT NULL,
	[status] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[archived_at] [datetimeoffset](3) NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
	[updated_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_product_variant] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_var_sku] UNIQUE NONCLUSTERED 
(
	[sku] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[product_variant] ADD  CONSTRAINT [df_var_tax]  DEFAULT ((0.1400)) FOR [tax_rate]
GO
ALTER TABLE [dbo].[product_variant] ADD  CONSTRAINT [df_var_weight]  DEFAULT ((0)) FOR [weight_grams]
GO
ALTER TABLE [dbo].[product_variant] ADD  CONSTRAINT [df_var_pos]  DEFAULT ((0)) FOR [position]
GO
ALTER TABLE [dbo].[product_variant] ADD  CONSTRAINT [df_var_status]  DEFAULT ('ACTIVE') FOR [status]
GO
ALTER TABLE [dbo].[product_variant] ADD  CONSTRAINT [df_var_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO
ALTER TABLE [dbo].[product_variant] ADD  CONSTRAINT [df_var_updated]  DEFAULT (sysdatetimeoffset()) FOR [updated_at]
GO
ALTER TABLE [dbo].[product_variant]  WITH CHECK ADD  CONSTRAINT [ck_var_price] CHECK  (([price]>=(0)))
GO
ALTER TABLE [dbo].[product_variant] CHECK CONSTRAINT [ck_var_price]
GO
ALTER TABLE [dbo].[product_variant]  WITH CHECK ADD  CONSTRAINT [ck_var_status] CHECK  (([status]='ARCHIVED' OR [status]='INACTIVE' OR [status]='ACTIVE'))
GO
ALTER TABLE [dbo].[product_variant] CHECK CONSTRAINT [ck_var_status]
GO

CREATE TABLE [dbo].[refresh_token](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[user_id] [bigint] NOT NULL,
	[token_hash] [varchar](255) COLLATE Arabic_CI_AS NOT NULL,
	[expires_at] [datetimeoffset](3) NOT NULL,
	[revoked_at] [datetimeoffset](3) NULL,
	[device_info] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_refresh_token] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_refresh_hash] UNIQUE NONCLUSTERED 
(
	[token_hash] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[refresh_token] ADD  CONSTRAINT [df_rt_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO

CREATE TABLE [dbo].[refund](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[order_id] [bigint] NOT NULL,
	[amount] [decimal](19, 4) NOT NULL,
	[method] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[reason] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[idempotency_key] [varchar](120) COLLATE Arabic_CI_AS NULL,
	[actor_id] [bigint] NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_refund] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[refund] ADD  CONSTRAINT [df_ref_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO
ALTER TABLE [dbo].[refund]  WITH CHECK ADD  CONSTRAINT [ck_ref_amount] CHECK  (([amount]>(0)))
GO
ALTER TABLE [dbo].[refund] CHECK CONSTRAINT [ck_ref_amount]
GO

CREATE TABLE [dbo].[return_item](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[return_id] [bigint] NOT NULL,
	[order_item_id] [bigint] NOT NULL,
	[quantity] [int] NOT NULL,
	[refund_amount] [decimal](19, 4) NOT NULL,
	[inspection_result] [varchar](20) COLLATE Arabic_CI_AS NULL,
	[inspection_note] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
 CONSTRAINT [pk_return_item] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[return_item] ADD  CONSTRAINT [df_ri_amount]  DEFAULT ((0)) FOR [refund_amount]
GO
ALTER TABLE [dbo].[return_item]  WITH CHECK ADD  CONSTRAINT [ck_ri_qty] CHECK  (([quantity]>(0)))
GO
ALTER TABLE [dbo].[return_item] CHECK CONSTRAINT [ck_ri_qty]
GO

CREATE TABLE [dbo].[return_request](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[order_id] [bigint] NOT NULL,
	[return_number] [varchar](30) COLLATE Arabic_CI_AS NOT NULL,
	[status] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[reason] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[customer_note] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
	[return_ship_payer] [varchar](20) COLLATE Arabic_CI_AS NULL,
	[requested_at] [datetimeoffset](3) NOT NULL,
	[approved_at] [datetimeoffset](3) NULL,
	[received_at] [datetimeoffset](3) NULL,
	[inspected_at] [datetimeoffset](3) NULL,
	[closed_at] [datetimeoffset](3) NULL,
 CONSTRAINT [pk_return_request] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_return_number] UNIQUE NONCLUSTERED 
(
	[return_number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[return_request] ADD  CONSTRAINT [df_ret_status]  DEFAULT ('REQUESTED') FOR [status]
GO
ALTER TABLE [dbo].[return_request] ADD  CONSTRAINT [df_ret_req]  DEFAULT (sysdatetimeoffset()) FOR [requested_at]
GO
ALTER TABLE [dbo].[return_request]  WITH CHECK ADD  CONSTRAINT [ck_ret_status] CHECK  (([status]='CLOSED' OR [status]='REFUNDED' OR [status]='INSPECTED' OR [status]='RECEIVED' OR [status]='REJECTED' OR [status]='APPROVED' OR [status]='REQUESTED'))
GO
ALTER TABLE [dbo].[return_request] CHECK CONSTRAINT [ck_ret_status]
GO

CREATE TABLE [dbo].[role](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[code] [varchar](50) COLLATE Arabic_CI_AS NOT NULL,
	[name_ar] [nvarchar](100) COLLATE Arabic_CI_AS NOT NULL,
	[name_en] [nvarchar](100) COLLATE Arabic_CI_AS NOT NULL,
	[is_system] [bit] NOT NULL,
 CONSTRAINT [pk_role] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_role_code] UNIQUE NONCLUSTERED 
(
	[code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[role] ADD  CONSTRAINT [df_role_system]  DEFAULT ((0)) FOR [is_system]
GO

CREATE TABLE [dbo].[role_permission](
	[role_id] [bigint] NOT NULL,
	[permission_id] [bigint] NOT NULL,
 CONSTRAINT [pk_role_permission] PRIMARY KEY CLUSTERED 
(
	[role_id] ASC,
	[permission_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO

CREATE TABLE [dbo].[shipment](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[order_id] [bigint] NOT NULL,
	[carrier_code] [varchar](30) COLLATE Arabic_CI_AS NULL,
	[tracking_number] [varchar](80) COLLATE Arabic_CI_AS NULL,
	[cod_amount] [decimal](19, 4) NOT NULL,
	[status] [varchar](30) COLLATE Arabic_CI_AS NOT NULL,
	[attempt_count] [smallint] NOT NULL,
	[failure_reason] [varchar](60) COLLATE Arabic_CI_AS NULL,
	[shipped_at] [datetimeoffset](3) NULL,
	[delivered_at] [datetimeoffset](3) NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_shipment] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[shipment] ADD  CONSTRAINT [df_shp_cod]  DEFAULT ((0)) FOR [cod_amount]
GO
ALTER TABLE [dbo].[shipment] ADD  CONSTRAINT [df_shp_status]  DEFAULT ('CREATED') FOR [status]
GO
ALTER TABLE [dbo].[shipment] ADD  CONSTRAINT [df_shp_attempts]  DEFAULT ((0)) FOR [attempt_count]
GO
ALTER TABLE [dbo].[shipment] ADD  CONSTRAINT [df_shp_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO

CREATE TABLE [dbo].[shipping_rate](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[zone_id] [bigint] NOT NULL,
	[base_cost] [decimal](19, 4) NOT NULL,
	[max_weight_grams] [int] NULL,
	[cost_per_extra_kg] [decimal](19, 4) NOT NULL,
	[free_shipping_over] [decimal](19, 4) NULL,
	[cod_fee] [decimal](19, 4) NOT NULL,
	[delivery_days_min] [smallint] NOT NULL,
	[delivery_days_max] [smallint] NOT NULL,
	[is_active] [bit] NOT NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
	[size_class] [varchar](10) COLLATE Arabic_CI_AS NOT NULL,
 CONSTRAINT [pk_shipping_rate] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[shipping_rate] ADD  CONSTRAINT [df_rate_extra]  DEFAULT ((0)) FOR [cost_per_extra_kg]
GO
ALTER TABLE [dbo].[shipping_rate] ADD  CONSTRAINT [df_rate_cod]  DEFAULT ((0)) FOR [cod_fee]
GO
ALTER TABLE [dbo].[shipping_rate] ADD  CONSTRAINT [df_rate_dmin]  DEFAULT ((2)) FOR [delivery_days_min]
GO
ALTER TABLE [dbo].[shipping_rate] ADD  CONSTRAINT [df_rate_dmax]  DEFAULT ((5)) FOR [delivery_days_max]
GO
ALTER TABLE [dbo].[shipping_rate] ADD  CONSTRAINT [df_rate_active]  DEFAULT ((1)) FOR [is_active]
GO
ALTER TABLE [dbo].[shipping_rate] ADD  CONSTRAINT [df_rate_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO
ALTER TABLE [dbo].[shipping_rate]  WITH CHECK ADD  CONSTRAINT [CK_shipping_rate_size_class] CHECK  (([size_class]='LARGE' OR [size_class]='MEDIUM' OR [size_class]='SMALL'))
GO
ALTER TABLE [dbo].[shipping_rate] CHECK CONSTRAINT [CK_shipping_rate_size_class]
GO

CREATE TABLE [dbo].[shipping_zone](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[code] [varchar](30) COLLATE Arabic_CI_AS NOT NULL,
	[name_ar] [nvarchar](100) COLLATE Arabic_CI_AS NOT NULL,
	[name_en] [nvarchar](100) COLLATE Arabic_CI_AS NOT NULL,
	[is_active] [bit] NOT NULL,
	[max_shipping_cost] [decimal](19, 4) NULL,
 CONSTRAINT [pk_shipping_zone] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_zone_code] UNIQUE NONCLUSTERED 
(
	[code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[shipping_zone] ADD  CONSTRAINT [df_zone_active]  DEFAULT ((1)) FOR [is_active]
GO

CREATE TABLE [dbo].[shipping_zone_governorate](
	[governorate_id] [bigint] NOT NULL,
	[zone_id] [bigint] NOT NULL,
 CONSTRAINT [pk_zone_gov] PRIMARY KEY CLUSTERED 
(
	[governorate_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO

CREATE TABLE [dbo].[stock_movement](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[variant_id] [bigint] NOT NULL,
	[movement_type] [varchar](30) COLLATE Arabic_CI_AS NOT NULL,
	[quantity_delta] [int] NOT NULL,
	[qty_after] [int] NOT NULL,
	[reference_type] [varchar](30) COLLATE Arabic_CI_AS NULL,
	[reference_id] [varchar](60) COLLATE Arabic_CI_AS NULL,
	[reason] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
	[actor_id] [bigint] NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
	[actor_name] [nvarchar](150) COLLATE Arabic_CI_AS NULL,
 CONSTRAINT [pk_stock_movement] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[stock_movement] ADD  CONSTRAINT [df_mov_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO
ALTER TABLE [dbo].[stock_movement]  WITH CHECK ADD  CONSTRAINT [ck_mov_type] CHECK  (([movement_type]='MANUAL_ADJUSTMENT' OR [movement_type]='DAMAGE_WRITEOFF' OR [movement_type]='RETURN_DAMAGED' OR [movement_type]='RETURN_SELLABLE' OR [movement_type]='CANCELLATION_RESTOCK' OR [movement_type]='SALE' OR [movement_type]='PURCHASE_RECEIVED'))
GO
ALTER TABLE [dbo].[stock_movement] CHECK CONSTRAINT [ck_mov_type]
GO

CREATE TABLE [dbo].[stock_reservation](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[variant_id] [bigint] NOT NULL,
	[order_id] [bigint] NULL,
	[cart_id] [bigint] NULL,
	[quantity] [int] NOT NULL,
	[status] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[expires_at] [datetimeoffset](3) NOT NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_stock_reservation] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[stock_reservation] ADD  CONSTRAINT [df_res_status]  DEFAULT ('HELD') FOR [status]
GO
ALTER TABLE [dbo].[stock_reservation] ADD  CONSTRAINT [df_res_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO
ALTER TABLE [dbo].[stock_reservation]  WITH CHECK ADD  CONSTRAINT [ck_res_qty] CHECK  (([quantity]>(0)))
GO
ALTER TABLE [dbo].[stock_reservation] CHECK CONSTRAINT [ck_res_qty]
GO
ALTER TABLE [dbo].[stock_reservation]  WITH CHECK ADD  CONSTRAINT [ck_res_status] CHECK  (([status]='EXPIRED' OR [status]='RELEASED' OR [status]='COMMITTED' OR [status]='HELD'))
GO
ALTER TABLE [dbo].[stock_reservation] CHECK CONSTRAINT [ck_res_status]
GO

CREATE TABLE [dbo].[store_profile](
	[id] [int] NOT NULL,
	[legal_name] [nvarchar](200) COLLATE Arabic_CI_AS NOT NULL,
	[legal_name_en] [nvarchar](200) COLLATE Arabic_CI_AS NULL,
	[address] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
	[phone] [nvarchar](30) COLLATE Arabic_CI_AS NULL,
	[email] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[tax_number] [nvarchar](30) COLLATE Arabic_CI_AS NULL,
	[commercial_register] [nvarchar](30) COLLATE Arabic_CI_AS NULL,
	[website] [nvarchar](255) COLLATE Arabic_CI_AS NULL,
	[invoice_footer_note] [nvarchar](500) COLLATE Arabic_CI_AS NULL,
	[updated_at] [datetimeoffset](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[store_profile] ADD  DEFAULT (sysdatetimeoffset()) FOR [updated_at]
GO
ALTER TABLE [dbo].[store_profile]  WITH CHECK ADD  CONSTRAINT [ck_store_profile_single_row] CHECK  (([id]=(1)))
GO
ALTER TABLE [dbo].[store_profile] CHECK CONSTRAINT [ck_store_profile_single_row]
GO

CREATE TABLE [dbo].[store_setting](
	[key] [varchar](80) COLLATE Arabic_CI_AS NOT NULL,
	[value] [nvarchar](max) COLLATE Arabic_CI_AS NULL,
	[value_type] [varchar](20) COLLATE Arabic_CI_AS NOT NULL,
	[updated_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_store_setting] PRIMARY KEY CLUSTERED 
(
	[key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[store_setting] ADD  CONSTRAINT [df_ss_type]  DEFAULT ('STRING') FOR [value_type]
GO
ALTER TABLE [dbo].[store_setting] ADD  CONSTRAINT [df_ss_updated]  DEFAULT (sysdatetimeoffset()) FOR [updated_at]
GO

CREATE TABLE [dbo].[url_redirect](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[old_path] [varchar](300) COLLATE Arabic_CI_AS NOT NULL,
	[new_path] [varchar](300) COLLATE Arabic_CI_AS NOT NULL,
	[status_code] [smallint] NOT NULL,
	[created_at] [datetimeoffset](3) NOT NULL,
 CONSTRAINT [pk_url_redirect] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF),
 CONSTRAINT [uq_rd_old] UNIQUE NONCLUSTERED 
(
	[old_path] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO
ALTER TABLE [dbo].[url_redirect] ADD  CONSTRAINT [df_rd_code]  DEFAULT ((301)) FOR [status_code]
GO
ALTER TABLE [dbo].[url_redirect] ADD  CONSTRAINT [df_rd_created]  DEFAULT (sysdatetimeoffset()) FOR [created_at]
GO

CREATE TABLE [dbo].[user_role](
	[user_id] [bigint] NOT NULL,
	[role_id] [bigint] NOT NULL,
 CONSTRAINT [pk_user_role] PRIMARY KEY CLUSTERED 
(
	[user_id] ASC,
	[role_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO

CREATE TABLE [dbo].[variant_attribute_value](
	[variant_id] [bigint] NOT NULL,
	[attribute_id] [bigint] NOT NULL,
	[attribute_value_id] [bigint] NOT NULL,
 CONSTRAINT [pk_vav] PRIMARY KEY CLUSTERED 
(
	[variant_id] ASC,
	[attribute_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
)
GO

/* ---------------- indexes ---------------- */
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [ux_user_email] ON [dbo].[app_user]
(
	[email] ASC
)
WHERE ([email] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [ux_user_phone] ON [dbo].[app_user]
(
	[phone_e164] ASC
)
WHERE ([phone_e164] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ix_audit_action] ON [dbo].[audit_log]
(
	[action] ASC,
	[created_at] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_audit_actor] ON [dbo].[audit_log]
(
	[actor_id] ASC,
	[created_at] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_audit_created] ON [dbo].[audit_log]
(
	[created_at] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ix_audit_entity] ON [dbo].[audit_log]
(
	[entity_type] ASC,
	[entity_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_bis_variant] ON [dbo].[back_in_stock_subscription]
(
	[variant_id] ASC
)
WHERE ([notified_at] IS NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE UNIQUE NONCLUSTERED INDEX [ux_cart_user] ON [dbo].[cart]
(
	[user_id] ASC
)
WHERE ([status]='ACTIVE' AND [user_id] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_cat_parent] ON [dbo].[category]
(
	[parent_id] ASC
)
WHERE ([is_active]=(1))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_city_gov] ON [dbo].[city]
(
	[governorate_id] ASC
)
WHERE ([is_active]=(1))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_remittance_date] ON [dbo].[cod_remittance]
(
	[settlement_date] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [uq_remittance_reference] ON [dbo].[cod_remittance]
(
	[reference] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_remittance_item_batch] ON [dbo].[cod_remittance_item]
(
	[remittance_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE UNIQUE NONCLUSTERED INDEX [uq_remittance_item_order] ON [dbo].[cod_remittance_item]
(
	[order_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ix_custom_req_phone] ON [dbo].[custom_order_request]
(
	[phone] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ix_custom_req_status] ON [dbo].[custom_order_request]
(
	[status] ASC,
	[created_at] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [uq_custom_req_number] ON [dbo].[custom_order_request]
(
	[request_number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE UNIQUE NONCLUSTERED INDEX [uq_custom_req_year_seq] ON [dbo].[custom_order_request]
(
	[fiscal_year] ASC,
	[sequence_number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_custom_req_att_request] ON [dbo].[custom_order_request_attachment]
(
	[request_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_addr_user] ON [dbo].[customer_address]
(
	[user_id] ASC
)
WHERE ([deleted_at] IS NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE UNIQUE NONCLUSTERED INDEX [ux_addr_default] ON [dbo].[customer_address]
(
	[user_id] ASC
)
WHERE ([is_default]=(1) AND [deleted_at] IS NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_ord_customer] ON [dbo].[customer_order]
(
	[customer_id] ASC,
	[placed_at] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ix_ord_fulfil] ON [dbo].[customer_order]
(
	[fulfillment_status] ASC,
	[placed_at] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_ord_gov] ON [dbo].[customer_order]
(
	[ship_governorate_id] ASC,
	[placed_at] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ix_ord_payment] ON [dbo].[customer_order]
(
	[payment_status] ASC
)
WHERE ([payment_status]='PENDING')
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ix_ord_phone] ON [dbo].[customer_order]
(
	[contact_phone] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_idem_expires] ON [dbo].[idempotency_key]
(
	[expires_at] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [uq_idem_key_endpoint] ON [dbo].[idempotency_key]
(
	[idempotency_key] ASC,
	[endpoint] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [ux_inventory_variant] ON [dbo].[inventory]
(
	[variant_id] ASC,
	[location_code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_invoice_issued] ON [dbo].[invoice]
(
	[issued_at] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [uq_invoice_number] ON [dbo].[invoice]
(
	[invoice_number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE UNIQUE NONCLUSTERED INDEX [uq_invoice_order] ON [dbo].[invoice]
(
	[order_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE UNIQUE NONCLUSTERED INDEX [uq_invoice_year_seq] ON [dbo].[invoice]
(
	[fiscal_year] ASC,
	[sequence_number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_nl_order] ON [dbo].[notification_log]
(
	[order_id] ASC,
	[created_at] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_oi_order] ON [dbo].[order_item]
(
	[order_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_oi_variant] ON [dbo].[order_item]
(
	[variant_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_osh_order] ON [dbo].[order_status_history]
(
	[order_id] ASC,
	[created_at] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ix_otp_lookup] ON [dbo].[otp_verification]
(
	[destination] ASC,
	[purpose] ASC,
	[expires_at] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [ux_pt_idempotency] ON [dbo].[payment_transaction]
(
	[idempotency_key] ASC
)
WHERE ([idempotency_key] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [ux_pt_provider_ref] ON [dbo].[payment_transaction]
(
	[provider] ASC,
	[provider_reference] ASC
)
WHERE ([provider_reference] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_prod_brand] ON [dbo].[product]
(
	[brand_id] ASC
)
WHERE ([archived_at] IS NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ix_prod_category] ON [dbo].[product]
(
	[category_id] ASC,
	[status] ASC
)
WHERE ([archived_at] IS NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_prod_featured] ON [dbo].[product]
(
	[is_featured] ASC
)
WHERE ([status]='ACTIVE')
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_img_product] ON [dbo].[product_image]
(
	[product_id] ASC,
	[display_order] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_img_variant] ON [dbo].[product_image]
(
	[variant_id] ASC
)
WHERE ([variant_id] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ix_prod_search] ON [dbo].[product_translation]
(
	[locale] ASC,
	[search_text] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_var_price] ON [dbo].[product_variant]
(
	[price] ASC
)
WHERE ([status]='ACTIVE')
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_var_product] ON [dbo].[product_variant]
(
	[product_id] ASC
)
WHERE ([archived_at] IS NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [ux_var_barcode] ON [dbo].[product_variant]
(
	[barcode] ASC
)
WHERE ([barcode] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_refresh_user] ON [dbo].[refresh_token]
(
	[user_id] ASC
)
WHERE ([revoked_at] IS NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [ux_refund_idem] ON [dbo].[refund]
(
	[idempotency_key] ASC
)
WHERE ([idempotency_key] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_ret_order] ON [dbo].[return_request]
(
	[order_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_shp_order] ON [dbo].[shipment]
(
	[order_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [ix_shp_tracking] ON [dbo].[shipment]
(
	[tracking_number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_rate_zone] ON [dbo].[shipping_rate]
(
	[zone_id] ASC
)
WHERE ([is_active]=(1))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [UX_shipping_rate_zone_size] ON [dbo].[shipping_rate]
(
	[zone_id] ASC,
	[size_class] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_zg_zone] ON [dbo].[shipping_zone_governorate]
(
	[zone_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_mov_variant] ON [dbo].[stock_movement]
(
	[variant_id] ASC,
	[created_at] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_res_expiry] ON [dbo].[stock_reservation]
(
	[expires_at] ASC
)
WHERE ([status]='HELD')
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_res_order] ON [dbo].[stock_reservation]
(
	[order_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
CREATE NONCLUSTERED INDEX [ix_vav_value] ON [dbo].[variant_attribute_value]
(
	[attribute_value_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO

/* ---------------- foreign keys ---------------- */
GO
ALTER TABLE [dbo].[attribute_translation]  WITH CHECK ADD  CONSTRAINT [fk_attr_tr] FOREIGN KEY([attribute_id])
REFERENCES [dbo].[attribute] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[attribute_translation] CHECK CONSTRAINT [fk_attr_tr]
GO
ALTER TABLE [dbo].[attribute_value]  WITH CHECK ADD  CONSTRAINT [fk_av_attr] FOREIGN KEY([attribute_id])
REFERENCES [dbo].[attribute] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[attribute_value] CHECK CONSTRAINT [fk_av_attr]
GO
ALTER TABLE [dbo].[attribute_value_translation]  WITH CHECK ADD  CONSTRAINT [fk_av_tr] FOREIGN KEY([attribute_value_id])
REFERENCES [dbo].[attribute_value] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[attribute_value_translation] CHECK CONSTRAINT [fk_av_tr]
GO
ALTER TABLE [dbo].[back_in_stock_subscription]  WITH CHECK ADD  CONSTRAINT [fk_bis_user] FOREIGN KEY([user_id])
REFERENCES [dbo].[app_user] ([id])
GO
ALTER TABLE [dbo].[back_in_stock_subscription] CHECK CONSTRAINT [fk_bis_user]
GO
ALTER TABLE [dbo].[back_in_stock_subscription]  WITH CHECK ADD  CONSTRAINT [fk_bis_variant] FOREIGN KEY([variant_id])
REFERENCES [dbo].[product_variant] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[back_in_stock_subscription] CHECK CONSTRAINT [fk_bis_variant]
GO
ALTER TABLE [dbo].[cart]  WITH CHECK ADD  CONSTRAINT [fk_cart_user] FOREIGN KEY([user_id])
REFERENCES [dbo].[app_user] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[cart] CHECK CONSTRAINT [fk_cart_user]
GO
ALTER TABLE [dbo].[cart_item]  WITH CHECK ADD  CONSTRAINT [fk_ci_cart] FOREIGN KEY([cart_id])
REFERENCES [dbo].[cart] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[cart_item] CHECK CONSTRAINT [fk_ci_cart]
GO
ALTER TABLE [dbo].[cart_item]  WITH CHECK ADD  CONSTRAINT [fk_ci_variant] FOREIGN KEY([variant_id])
REFERENCES [dbo].[product_variant] ([id])
GO
ALTER TABLE [dbo].[cart_item] CHECK CONSTRAINT [fk_ci_variant]
GO
ALTER TABLE [dbo].[category]  WITH CHECK ADD  CONSTRAINT [fk_cat_parent] FOREIGN KEY([parent_id])
REFERENCES [dbo].[category] ([id])
GO
ALTER TABLE [dbo].[category] CHECK CONSTRAINT [fk_cat_parent]
GO
ALTER TABLE [dbo].[category_attribute]  WITH CHECK ADD  CONSTRAINT [fk_ca_attr] FOREIGN KEY([attribute_id])
REFERENCES [dbo].[attribute] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[category_attribute] CHECK CONSTRAINT [fk_ca_attr]
GO
ALTER TABLE [dbo].[category_attribute]  WITH CHECK ADD  CONSTRAINT [fk_ca_cat] FOREIGN KEY([category_id])
REFERENCES [dbo].[category] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[category_attribute] CHECK CONSTRAINT [fk_ca_cat]
GO
ALTER TABLE [dbo].[category_translation]  WITH CHECK ADD  CONSTRAINT [fk_cat_tr] FOREIGN KEY([category_id])
REFERENCES [dbo].[category] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[category_translation] CHECK CONSTRAINT [fk_cat_tr]
GO
ALTER TABLE [dbo].[city]  WITH CHECK ADD  CONSTRAINT [fk_city_gov] FOREIGN KEY([governorate_id])
REFERENCES [dbo].[governorate] ([id])
GO
ALTER TABLE [dbo].[city] CHECK CONSTRAINT [fk_city_gov]
GO
ALTER TABLE [dbo].[cod_remittance_item]  WITH CHECK ADD  CONSTRAINT [fk_remittance_item_batch] FOREIGN KEY([remittance_id])
REFERENCES [dbo].[cod_remittance] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[cod_remittance_item] CHECK CONSTRAINT [fk_remittance_item_batch]
GO
ALTER TABLE [dbo].[cod_remittance_item]  WITH CHECK ADD  CONSTRAINT [fk_remittance_item_order] FOREIGN KEY([order_id])
REFERENCES [dbo].[customer_order] ([id])
GO
ALTER TABLE [dbo].[cod_remittance_item] CHECK CONSTRAINT [fk_remittance_item_order]
GO
ALTER TABLE [dbo].[custom_order_request]  WITH CHECK ADD  CONSTRAINT [fk_custom_req_customer] FOREIGN KEY([customer_id])
REFERENCES [dbo].[app_user] ([id])
GO
ALTER TABLE [dbo].[custom_order_request] CHECK CONSTRAINT [fk_custom_req_customer]
GO
ALTER TABLE [dbo].[custom_order_request]  WITH CHECK ADD  CONSTRAINT [fk_custom_req_governorate] FOREIGN KEY([governorate_id])
REFERENCES [dbo].[governorate] ([id])
GO
ALTER TABLE [dbo].[custom_order_request] CHECK CONSTRAINT [fk_custom_req_governorate]
GO
ALTER TABLE [dbo].[custom_order_request]  WITH CHECK ADD  CONSTRAINT [fk_custom_req_order] FOREIGN KEY([converted_order_id])
REFERENCES [dbo].[customer_order] ([id])
GO
ALTER TABLE [dbo].[custom_order_request] CHECK CONSTRAINT [fk_custom_req_order]
GO
ALTER TABLE [dbo].[custom_order_request]  WITH CHECK ADD  CONSTRAINT [fk_custom_req_product] FOREIGN KEY([product_id])
REFERENCES [dbo].[product] ([id])
GO
ALTER TABLE [dbo].[custom_order_request] CHECK CONSTRAINT [fk_custom_req_product]
GO
ALTER TABLE [dbo].[custom_order_request_attachment]  WITH CHECK ADD  CONSTRAINT [fk_custom_req_att_request] FOREIGN KEY([request_id])
REFERENCES [dbo].[custom_order_request] ([id])
GO
ALTER TABLE [dbo].[custom_order_request_attachment] CHECK CONSTRAINT [fk_custom_req_att_request]
GO
ALTER TABLE [dbo].[customer_address]  WITH CHECK ADD  CONSTRAINT [fk_addr_city] FOREIGN KEY([city_id])
REFERENCES [dbo].[city] ([id])
GO
ALTER TABLE [dbo].[customer_address] CHECK CONSTRAINT [fk_addr_city]
GO
ALTER TABLE [dbo].[customer_address]  WITH CHECK ADD  CONSTRAINT [fk_addr_gov] FOREIGN KEY([governorate_id])
REFERENCES [dbo].[governorate] ([id])
GO
ALTER TABLE [dbo].[customer_address] CHECK CONSTRAINT [fk_addr_gov]
GO
ALTER TABLE [dbo].[customer_address]  WITH CHECK ADD  CONSTRAINT [fk_addr_user] FOREIGN KEY([user_id])
REFERENCES [dbo].[app_user] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[customer_address] CHECK CONSTRAINT [fk_addr_user]
GO
ALTER TABLE [dbo].[customer_order]  WITH CHECK ADD  CONSTRAINT [fk_ord_customer] FOREIGN KEY([customer_id])
REFERENCES [dbo].[app_user] ([id])
GO
ALTER TABLE [dbo].[customer_order] CHECK CONSTRAINT [fk_ord_customer]
GO
ALTER TABLE [dbo].[customer_order]  WITH CHECK ADD  CONSTRAINT [fk_ord_gov] FOREIGN KEY([ship_governorate_id])
REFERENCES [dbo].[governorate] ([id])
GO
ALTER TABLE [dbo].[customer_order] CHECK CONSTRAINT [fk_ord_gov]
GO
ALTER TABLE [dbo].[inventory]  WITH CHECK ADD  CONSTRAINT [fk_inv_variant] FOREIGN KEY([variant_id])
REFERENCES [dbo].[product_variant] ([id])
GO
ALTER TABLE [dbo].[inventory] CHECK CONSTRAINT [fk_inv_variant]
GO
ALTER TABLE [dbo].[invoice]  WITH CHECK ADD  CONSTRAINT [fk_invoice_order] FOREIGN KEY([order_id])
REFERENCES [dbo].[customer_order] ([id])
GO
ALTER TABLE [dbo].[invoice] CHECK CONSTRAINT [fk_invoice_order]
GO
ALTER TABLE [dbo].[notification_log]  WITH CHECK ADD  CONSTRAINT [fk_nl_order] FOREIGN KEY([order_id])
REFERENCES [dbo].[customer_order] ([id])
GO
ALTER TABLE [dbo].[notification_log] CHECK CONSTRAINT [fk_nl_order]
GO
ALTER TABLE [dbo].[order_item]  WITH CHECK ADD  CONSTRAINT [fk_oi_order] FOREIGN KEY([order_id])
REFERENCES [dbo].[customer_order] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[order_item] CHECK CONSTRAINT [fk_oi_order]
GO
ALTER TABLE [dbo].[order_item]  WITH CHECK ADD  CONSTRAINT [fk_oi_product] FOREIGN KEY([product_id])
REFERENCES [dbo].[product] ([id])
GO
ALTER TABLE [dbo].[order_item] CHECK CONSTRAINT [fk_oi_product]
GO
ALTER TABLE [dbo].[order_item]  WITH CHECK ADD  CONSTRAINT [fk_oi_variant] FOREIGN KEY([variant_id])
REFERENCES [dbo].[product_variant] ([id])
GO
ALTER TABLE [dbo].[order_item] CHECK CONSTRAINT [fk_oi_variant]
GO
ALTER TABLE [dbo].[order_status_history]  WITH CHECK ADD  CONSTRAINT [fk_osh_actor] FOREIGN KEY([actor_id])
REFERENCES [dbo].[app_user] ([id])
GO
ALTER TABLE [dbo].[order_status_history] CHECK CONSTRAINT [fk_osh_actor]
GO
ALTER TABLE [dbo].[order_status_history]  WITH CHECK ADD  CONSTRAINT [fk_osh_order] FOREIGN KEY([order_id])
REFERENCES [dbo].[customer_order] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[order_status_history] CHECK CONSTRAINT [fk_osh_order]
GO
ALTER TABLE [dbo].[otp_verification]  WITH CHECK ADD  CONSTRAINT [fk_otp_user] FOREIGN KEY([user_id])
REFERENCES [dbo].[app_user] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[otp_verification] CHECK CONSTRAINT [fk_otp_user]
GO
ALTER TABLE [dbo].[password_reset_token]  WITH CHECK ADD  CONSTRAINT [fk_prt_user] FOREIGN KEY([user_id])
REFERENCES [dbo].[app_user] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[password_reset_token] CHECK CONSTRAINT [fk_prt_user]
GO
ALTER TABLE [dbo].[payment_transaction]  WITH CHECK ADD  CONSTRAINT [fk_pt_order] FOREIGN KEY([order_id])
REFERENCES [dbo].[customer_order] ([id])
GO
ALTER TABLE [dbo].[payment_transaction] CHECK CONSTRAINT [fk_pt_order]
GO
ALTER TABLE [dbo].[product]  WITH CHECK ADD  CONSTRAINT [fk_prod_brand] FOREIGN KEY([brand_id])
REFERENCES [dbo].[brand] ([id])
GO
ALTER TABLE [dbo].[product] CHECK CONSTRAINT [fk_prod_brand]
GO
ALTER TABLE [dbo].[product]  WITH CHECK ADD  CONSTRAINT [fk_prod_cat] FOREIGN KEY([category_id])
REFERENCES [dbo].[category] ([id])
GO
ALTER TABLE [dbo].[product] CHECK CONSTRAINT [fk_prod_cat]
GO
ALTER TABLE [dbo].[product_attribute_value]  WITH CHECK ADD  CONSTRAINT [fk_pav_attr] FOREIGN KEY([attribute_id])
REFERENCES [dbo].[attribute] ([id])
GO
ALTER TABLE [dbo].[product_attribute_value] CHECK CONSTRAINT [fk_pav_attr]
GO
ALTER TABLE [dbo].[product_attribute_value]  WITH CHECK ADD  CONSTRAINT [fk_pav_prod] FOREIGN KEY([product_id])
REFERENCES [dbo].[product] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[product_attribute_value] CHECK CONSTRAINT [fk_pav_prod]
GO
ALTER TABLE [dbo].[product_attribute_value]  WITH CHECK ADD  CONSTRAINT [fk_pav_value] FOREIGN KEY([attribute_value_id])
REFERENCES [dbo].[attribute_value] ([id])
GO
ALTER TABLE [dbo].[product_attribute_value] CHECK CONSTRAINT [fk_pav_value]
GO
ALTER TABLE [dbo].[product_image]  WITH CHECK ADD  CONSTRAINT [fk_img_product] FOREIGN KEY([product_id])
REFERENCES [dbo].[product] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[product_image] CHECK CONSTRAINT [fk_img_product]
GO
ALTER TABLE [dbo].[product_image]  WITH CHECK ADD  CONSTRAINT [fk_img_variant] FOREIGN KEY([variant_id])
REFERENCES [dbo].[product_variant] ([id])
GO
ALTER TABLE [dbo].[product_image] CHECK CONSTRAINT [fk_img_variant]
GO
ALTER TABLE [dbo].[product_translation]  WITH CHECK ADD  CONSTRAINT [fk_prod_tr] FOREIGN KEY([product_id])
REFERENCES [dbo].[product] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[product_translation] CHECK CONSTRAINT [fk_prod_tr]
GO
ALTER TABLE [dbo].[product_variant]  WITH CHECK ADD  CONSTRAINT [fk_var_product] FOREIGN KEY([product_id])
REFERENCES [dbo].[product] ([id])
GO
ALTER TABLE [dbo].[product_variant] CHECK CONSTRAINT [fk_var_product]
GO
ALTER TABLE [dbo].[refresh_token]  WITH CHECK ADD  CONSTRAINT [fk_rt_user] FOREIGN KEY([user_id])
REFERENCES [dbo].[app_user] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[refresh_token] CHECK CONSTRAINT [fk_rt_user]
GO
ALTER TABLE [dbo].[refund]  WITH CHECK ADD  CONSTRAINT [fk_ref_actor] FOREIGN KEY([actor_id])
REFERENCES [dbo].[app_user] ([id])
GO
ALTER TABLE [dbo].[refund] CHECK CONSTRAINT [fk_ref_actor]
GO
ALTER TABLE [dbo].[refund]  WITH CHECK ADD  CONSTRAINT [fk_ref_order] FOREIGN KEY([order_id])
REFERENCES [dbo].[customer_order] ([id])
GO
ALTER TABLE [dbo].[refund] CHECK CONSTRAINT [fk_ref_order]
GO
ALTER TABLE [dbo].[return_item]  WITH CHECK ADD  CONSTRAINT [fk_ri_item] FOREIGN KEY([order_item_id])
REFERENCES [dbo].[order_item] ([id])
GO
ALTER TABLE [dbo].[return_item] CHECK CONSTRAINT [fk_ri_item]
GO
ALTER TABLE [dbo].[return_item]  WITH CHECK ADD  CONSTRAINT [fk_ri_return] FOREIGN KEY([return_id])
REFERENCES [dbo].[return_request] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[return_item] CHECK CONSTRAINT [fk_ri_return]
GO
ALTER TABLE [dbo].[return_request]  WITH CHECK ADD  CONSTRAINT [fk_ret_order] FOREIGN KEY([order_id])
REFERENCES [dbo].[customer_order] ([id])
GO
ALTER TABLE [dbo].[return_request] CHECK CONSTRAINT [fk_ret_order]
GO
ALTER TABLE [dbo].[role_permission]  WITH CHECK ADD  CONSTRAINT [fk_rp_permission] FOREIGN KEY([permission_id])
REFERENCES [dbo].[permission] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[role_permission] CHECK CONSTRAINT [fk_rp_permission]
GO
ALTER TABLE [dbo].[role_permission]  WITH CHECK ADD  CONSTRAINT [fk_rp_role] FOREIGN KEY([role_id])
REFERENCES [dbo].[role] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[role_permission] CHECK CONSTRAINT [fk_rp_role]
GO
ALTER TABLE [dbo].[shipment]  WITH CHECK ADD  CONSTRAINT [fk_shp_order] FOREIGN KEY([order_id])
REFERENCES [dbo].[customer_order] ([id])
GO
ALTER TABLE [dbo].[shipment] CHECK CONSTRAINT [fk_shp_order]
GO
ALTER TABLE [dbo].[shipping_rate]  WITH CHECK ADD  CONSTRAINT [fk_rate_zone] FOREIGN KEY([zone_id])
REFERENCES [dbo].[shipping_zone] ([id])
GO
ALTER TABLE [dbo].[shipping_rate] CHECK CONSTRAINT [fk_rate_zone]
GO
ALTER TABLE [dbo].[shipping_zone_governorate]  WITH CHECK ADD  CONSTRAINT [fk_zg_gov] FOREIGN KEY([governorate_id])
REFERENCES [dbo].[governorate] ([id])
GO
ALTER TABLE [dbo].[shipping_zone_governorate] CHECK CONSTRAINT [fk_zg_gov]
GO
ALTER TABLE [dbo].[shipping_zone_governorate]  WITH CHECK ADD  CONSTRAINT [fk_zg_zone] FOREIGN KEY([zone_id])
REFERENCES [dbo].[shipping_zone] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[shipping_zone_governorate] CHECK CONSTRAINT [fk_zg_zone]
GO
ALTER TABLE [dbo].[stock_movement]  WITH CHECK ADD  CONSTRAINT [fk_mov_actor] FOREIGN KEY([actor_id])
REFERENCES [dbo].[app_user] ([id])
GO
ALTER TABLE [dbo].[stock_movement] CHECK CONSTRAINT [fk_mov_actor]
GO
ALTER TABLE [dbo].[stock_movement]  WITH CHECK ADD  CONSTRAINT [fk_mov_variant] FOREIGN KEY([variant_id])
REFERENCES [dbo].[product_variant] ([id])
GO
ALTER TABLE [dbo].[stock_movement] CHECK CONSTRAINT [fk_mov_variant]
GO
ALTER TABLE [dbo].[stock_reservation]  WITH CHECK ADD  CONSTRAINT [fk_res_cart] FOREIGN KEY([cart_id])
REFERENCES [dbo].[cart] ([id])
GO
ALTER TABLE [dbo].[stock_reservation] CHECK CONSTRAINT [fk_res_cart]
GO
ALTER TABLE [dbo].[stock_reservation]  WITH CHECK ADD  CONSTRAINT [fk_res_order] FOREIGN KEY([order_id])
REFERENCES [dbo].[customer_order] ([id])
GO
ALTER TABLE [dbo].[stock_reservation] CHECK CONSTRAINT [fk_res_order]
GO
ALTER TABLE [dbo].[stock_reservation]  WITH CHECK ADD  CONSTRAINT [fk_res_variant] FOREIGN KEY([variant_id])
REFERENCES [dbo].[product_variant] ([id])
GO
ALTER TABLE [dbo].[stock_reservation] CHECK CONSTRAINT [fk_res_variant]
GO
ALTER TABLE [dbo].[user_role]  WITH CHECK ADD  CONSTRAINT [fk_ur_role] FOREIGN KEY([role_id])
REFERENCES [dbo].[role] ([id])
GO
ALTER TABLE [dbo].[user_role] CHECK CONSTRAINT [fk_ur_role]
GO
ALTER TABLE [dbo].[user_role]  WITH CHECK ADD  CONSTRAINT [fk_ur_user] FOREIGN KEY([user_id])
REFERENCES [dbo].[app_user] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[user_role] CHECK CONSTRAINT [fk_ur_user]
GO
ALTER TABLE [dbo].[variant_attribute_value]  WITH CHECK ADD  CONSTRAINT [fk_vav_attr] FOREIGN KEY([attribute_id])
REFERENCES [dbo].[attribute] ([id])
GO
ALTER TABLE [dbo].[variant_attribute_value] CHECK CONSTRAINT [fk_vav_attr]
GO
ALTER TABLE [dbo].[variant_attribute_value]  WITH CHECK ADD  CONSTRAINT [fk_vav_value] FOREIGN KEY([attribute_value_id])
REFERENCES [dbo].[attribute_value] ([id])
GO
ALTER TABLE [dbo].[variant_attribute_value] CHECK CONSTRAINT [fk_vav_value]
GO
ALTER TABLE [dbo].[variant_attribute_value]  WITH CHECK ADD  CONSTRAINT [fk_vav_variant] FOREIGN KEY([variant_id])
REFERENCES [dbo].[product_variant] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[variant_attribute_value] CHECK CONSTRAINT [fk_vav_variant]
GO

/* ---------------- views ---------------- */
GO


/* =====================================================================
   12. HELPER VIEW — available stock, the number shown to customers
   ===================================================================== */

CREATE VIEW v_variant_availability AS
SELECT
    v.id                                     AS variant_id,
    v.product_id,
    v.sku,
    v.price,
    i.qty_on_hand,
    i.qty_reserved,
    (i.qty_on_hand - i.qty_reserved)         AS qty_available,
    CAST(CASE WHEN (i.qty_on_hand - i.qty_reserved) > 0
              THEN 1 ELSE 0 END AS BIT)      AS is_in_stock,
    CAST(CASE WHEN (i.qty_on_hand - i.qty_reserved) <= i.min_stock_level
              THEN 1 ELSE 0 END AS BIT)      AS is_low_stock
FROM product_variant v
INNER JOIN inventory i ON i.variant_id = v.id
WHERE v.status = 'ACTIVE' AND v.archived_at IS NULL;
GO
