/* =====================================================================
   Reference data the application needs on any database: roles, the 27 governorates, shipping zones, per-size rates and which zone each governorate is in (South Sinai, Aswan and Luxor are in none, i.e. closed).

   Generated by scripts/db/generate-seed.ps1 from the 'velora' database.
   Re-running is harmless: a table that already has rows is left alone.
   Apply with:  sqlcmd -f 65001 -b -d <database> -i <this file>
   ===================================================================== */

SET QUOTED_IDENTIFIER ON;
GO

/* role : 2 row(s) */
IF NOT EXISTS (SELECT 1 FROM dbo.[role])
BEGIN
    SET IDENTITY_INSERT dbo.[role] ON;
    INSERT INTO dbo.[role] ([id], [code], [name_ar], [name_en], [is_system]) VALUES
    (1, 'CUSTOMER', N'عميل', N'Customer', 1),
    (2, 'ADMIN', N'مدير النظام', N'Administrator', 1);
    SET IDENTITY_INSERT dbo.[role] OFF;
END
GO

/* governorate : 27 row(s) */
IF NOT EXISTS (SELECT 1 FROM dbo.[governorate])
BEGIN
    SET IDENTITY_INSERT dbo.[governorate] ON;
    INSERT INTO dbo.[governorate] ([id], [code], [name_ar], [name_en], [is_active], [display_order]) VALUES
    (1, 'CAI', N'القاهرة', N'Cairo', 1, 1),
    (2, 'GIZ', N'الجيزة', N'Giza', 1, 2),
    (3, 'QLY', N'القليوبية', N'Qalyubia', 1, 3),
    (4, 'ALX', N'الإسكندرية', N'Alexandria', 1, 4),
    (5, 'BEH', N'البحيرة', N'Beheira', 1, 5),
    (6, 'GHR', N'الغربية', N'Gharbia', 1, 6),
    (7, 'MNF', N'المنوفية', N'Monufia', 1, 7),
    (8, 'DAK', N'الدقهلية', N'Dakahlia', 1, 8),
    (9, 'SHR', N'الشرقية', N'Sharqia', 1, 9),
    (10, 'KFS', N'كفر الشيخ', N'Kafr El Sheikh', 1, 10),
    (11, 'DAM', N'دمياط', N'Damietta', 1, 11),
    (12, 'PTS', N'بورسعيد', N'Port Said', 1, 12),
    (13, 'ISM', N'الإسماعيلية', N'Ismailia', 1, 13),
    (14, 'SUZ', N'السويس', N'Suez', 1, 14),
    (15, 'NSI', N'شمال سيناء', N'North Sinai', 1, 15),
    (16, 'SSI', N'جنوب سيناء', N'South Sinai', 1, 16),
    (17, 'BNS', N'بني سويف', N'Beni Suef', 1, 17),
    (18, 'FYM', N'الفيوم', N'Faiyum', 1, 18),
    (19, 'MNY', N'المنيا', N'Minya', 1, 19),
    (20, 'AST', N'أسيوط', N'Asyut', 1, 20),
    (21, 'SHG', N'سوهاج', N'Sohag', 1, 21),
    (22, 'QNA', N'قنا', N'Qena', 1, 22),
    (23, 'LUX', N'الأقصر', N'Luxor', 1, 23),
    (24, 'ASW', N'أسوان', N'Aswan', 1, 24),
    (25, 'RSY', N'البحر الأحمر', N'Red Sea', 1, 25),
    (26, 'WAD', N'الوادي الجديد', N'New Valley', 1, 26),
    (27, 'MTR', N'مطروح', N'Matrouh', 1, 27);
    SET IDENTITY_INSERT dbo.[governorate] OFF;
END
GO

/* shipping_zone : 6 row(s) */
IF NOT EXISTS (SELECT 1 FROM dbo.[shipping_zone])
BEGIN
    SET IDENTITY_INSERT dbo.[shipping_zone] ON;
    INSERT INTO dbo.[shipping_zone] ([id], [code], [name_ar], [name_en], [is_active], [max_shipping_cost]) VALUES
    (1, 'GREATER_CAIRO', N'القاهرة الكبرى', N'Greater Cairo', 1, 1500.0000),
    (2, 'ALEXANDRIA', N'الإسكندرية', N'Alexandria', 1, 1500.0000),
    (3, 'DELTA', N'الدلتا', N'Delta', 1, 1500.0000),
    (4, 'CANAL', N'القناة', N'Canal', 1, 1500.0000),
    (5, 'UPPER_EGYPT', N'الصعيد', N'Upper Egypt', 1, 1500.0000),
    (6, 'REMOTE', N'المناطق النائية', N'Remote Areas', 1, 1500.0000);
    SET IDENTITY_INSERT dbo.[shipping_zone] OFF;
END
GO

/* shipping_rate : 18 row(s) */
IF NOT EXISTS (SELECT 1 FROM dbo.[shipping_rate])
BEGIN
    SET IDENTITY_INSERT dbo.[shipping_rate] ON;
    INSERT INTO dbo.[shipping_rate] ([id], [zone_id], [base_cost], [max_weight_grams], [cost_per_extra_kg], [free_shipping_over], [cod_fee], [delivery_days_min], [delivery_days_max], [is_active], [created_at], [size_class]) VALUES
    (10002, 2, 120.0000, NULL, 0.0000, NULL, 0.0000, 2, 4, 1, '2026-08-09 02:29:23.4580000+03:00', 'SMALL'),
    (10003, 4, 120.0000, NULL, 0.0000, NULL, 0.0000, 2, 4, 1, '2026-08-09 02:29:23.4580000+03:00', 'SMALL'),
    (10005, 1, 0.0000, NULL, 0.0000, NULL, 0.0000, 1, 3, 1, '2026-08-09 02:29:23.4580000+03:00', 'SMALL'),
    (10006, 6, 200.0000, NULL, 0.0000, NULL, 0.0000, 3, 8, 1, '2026-08-09 02:29:23.4580000+03:00', 'SMALL'),
    (10007, 5, 150.0000, NULL, 0.0000, NULL, 0.0000, 2, 5, 1, '2026-08-09 02:29:23.4580000+03:00', 'SMALL'),
    (10008, 2, 250.0000, NULL, 0.0000, NULL, 0.0000, 2, 4, 1, '2026-10-02 18:55:34.2800000+03:00', 'MEDIUM'),
    (10009, 2, 450.0000, NULL, 0.0000, NULL, 0.0000, 2, 4, 1, '2026-10-02 18:55:34.2800000+03:00', 'LARGE'),
    (10010, 4, 250.0000, NULL, 0.0000, NULL, 0.0000, 2, 4, 1, '2026-10-02 18:55:34.2800000+03:00', 'MEDIUM'),
    (10011, 4, 450.0000, NULL, 0.0000, NULL, 0.0000, 2, 4, 1, '2026-10-02 18:55:34.2800000+03:00', 'LARGE'),
    (10012, 3, 200.0000, NULL, 0.0000, NULL, 0.0000, 2, 4, 1, '2026-10-02 18:55:34.2800000+03:00', 'MEDIUM'),
    (10013, 3, 400.0000, NULL, 0.0000, NULL, 0.0000, 2, 4, 1, '2026-10-02 18:55:34.2800000+03:00', 'LARGE'),
    (10014, 1, 0.0000, NULL, 0.0000, NULL, 0.0000, 1, 3, 1, '2026-10-02 18:55:34.2800000+03:00', 'MEDIUM'),
    (10015, 1, 0.0000, NULL, 0.0000, NULL, 0.0000, 1, 3, 1, '2026-10-02 18:55:34.2800000+03:00', 'LARGE'),
    (10016, 6, 400.0000, NULL, 0.0000, NULL, 0.0000, 3, 8, 1, '2026-10-02 18:55:34.2800000+03:00', 'MEDIUM'),
    (10017, 6, 700.0000, NULL, 0.0000, NULL, 0.0000, 3, 8, 1, '2026-10-02 18:55:34.2800000+03:00', 'LARGE'),
    (10018, 5, 300.0000, NULL, 0.0000, NULL, 0.0000, 2, 5, 1, '2026-10-02 18:55:34.2800000+03:00', 'MEDIUM'),
    (10019, 5, 550.0000, NULL, 0.0000, NULL, 0.0000, 2, 5, 1, '2026-10-02 18:55:34.2800000+03:00', 'LARGE'),
    (10024, 3, 100.0000, NULL, 0.0000, NULL, 0.0000, 2, 4, 1, '2026-10-02 22:59:59.4680000+03:00', 'SMALL');
    SET IDENTITY_INSERT dbo.[shipping_rate] OFF;
END
GO

/* shipping_zone_governorate : 24 row(s) */
IF NOT EXISTS (SELECT 1 FROM dbo.[shipping_zone_governorate])
BEGIN
    INSERT INTO dbo.[shipping_zone_governorate] ([governorate_id], [zone_id]) VALUES
    (1, 1),
    (2, 1),
    (3, 1),
    (4, 2),
    (5, 3),
    (6, 3),
    (7, 3),
    (8, 3),
    (9, 3),
    (10, 3),
    (11, 3),
    (12, 4),
    (13, 4),
    (14, 4),
    (15, 6),
    (17, 5),
    (18, 5),
    (19, 5),
    (20, 5),
    (21, 5),
    (22, 5),
    (25, 6),
    (26, 6),
    (27, 6);
END
GO

