/* =====================================================================
   TEST-ONLY fixture: a seller profile, which invoice issuance requires. NEVER apply this to a real database - a real shop enters its own legal details.

   Generated by scripts/db/generate-seed.ps1 from the 'velora' database.
   The phone and email were REPLACED with placeholders after generating: the source row
   held a real person's contact details, which do not belong in the repository.
   Re-running is harmless: a table that already has rows is left alone.
   Apply with:  sqlcmd -f 65001 -b -d <database> -i <this file>
   ===================================================================== */

SET QUOTED_IDENTIFIER ON;
GO

/* store_profile : 1 row(s) */
IF NOT EXISTS (SELECT 1 FROM dbo.[store_profile])
BEGIN
    INSERT INTO dbo.[store_profile] ([id], [legal_name], [legal_name_en], [address], [phone], [email], [tax_number], [commercial_register], [website], [invoice_footer_note], [updated_at]) VALUES
    (1, N'VELORA', N'VELORA', N'القاهرة، مصر', N'01000000000', N'seller@example.com', NULL, NULL, NULL, N'شكراً لتسوقكم من فيلورا', '2026-08-10 17:48:41.7759942+03:00');
END
GO

